# The desktop checker, as a standalone directory `nix eval` can read.
#
# `haus show` has to answer "is this a desktop, and what does it set?" from a
# shell, offline, about a file that lives outside any flake. The rules already
# exist — modules/lib/desktop.nix over the room registry — but they are reachable
# only through the flake's `lib`, and reaching THAT from the CLI means resolving
# the consumer's lock and evaluating a flake, on every invocation, to answer a
# question that is pure lib.
#
# So the same three files are staged in the store with a `lib` beside them and an
# entry point that needs no arguments:
#
#   nix eval --impure --json --expr 'import <this>/read.nix "/abs/desktop.nix"'
#
# Two properties are why this is a copy rather than a second implementation.
# `desktop.nix` and `options-groups.nix` are the SAME files the flake evaluates —
# a rule can't drift between the seam and the CLI, because there is one of it.
# And the copy is built from the revision the machine is pinned to, the same
# argument host-template.nix makes: a checker that describes options your pin
# doesn't have is a failed publish for the person least able to debug it.
#
# nixpkgs' `lib` rides along, because a bare .nix file has no `lib` and the rules
# want one. It is self-contained by design — it is exactly what
# `import <nixpkgs/lib>` gives you — and 2 MB, so it is copied in rather than
# referred to at `pkgs.path`, which would root the WHOLE nixpkgs source in the
# system closure to borrow one directory of it.
#
# `builtins.path` and not a bare `${pkgs.path}/lib`: `pkgs.path` is a store path
# carrying no string CONTEXT, so interpolating it into a build script yields a
# derivation that MENTIONS a path it does not depend on — which Nix warns about
# ("this is unreliable and may stop working") and a garbage collector is free to
# make true. `builtins.path` copies the subtree in under its own name, with the
# context that makes the dependency real, and copies only `lib`.
{
  pkgs,
  lib ? pkgs.lib,
}:

let
  version = lib.fileContents ../VERSION;
  nixpkgsLib = builtins.path {
    path = "${pkgs.path}/lib";
    name = "nixpkgs-lib";
  };
  builtinDesktops = import ./desktop-names.nix;
in
pkgs.runCommand "haus-desktop-check-${version}"
  {
    meta = {
      description = "Standalone evaluator behind `haus show` — the desktop rules, offline";
      inherit version;
    };
  }
  ''
    dir="$out/share/haus/desktop-check"
    mkdir -p "$dir"

    cp -r ${nixpkgsLib} "$dir/lib"
    chmod -R u+w "$dir/lib"

    cp ${./options-groups.nix}       "$dir/registry.nix"
    cp ${./lib/desktop.nix}             "$dir/desktop.nix"
    # desktop.nix imports this for the reserved prefix, so the flake-less copy
    # needs it too — without it `haus show` dies on any file with a bad option
    # path, which is exactly the file people run it on.
    cp ${./lib/namespaces.nix}          "$dir/namespaces.nix"
    cp ${./lib/show.nix}                "$dir/show.nix"

    # And the launcher room's mirror of pounce's item-key grammar, which
    # `desktop.nix` reads to decide which palette addresses a desktop may name.
    # It stays in ./launcher rather than moving beside desktop.nix because it is
    # one of a PAIR of mirrors that room owns (./launcher/header-grammar.nix
    # names it as its sibling) — so the copy has to land where desktop.nix's
    # `../launcher/item-grammar.nix` points, which is one level ABOVE $dir, not
    # inside it.
    #
    # Nix is lazy, so getting this wrong fails in the one case that matters and
    # in no other: `itemGrammar` is forced only by a file that actually sets
    # `haus.launcher.items`, so every flake check and every other desktop still
    # passes while `haus show` dies on exactly the desktops this grammar exists
    # to admit. test/haus-show.sh has the regression for it.
    install -Dm644 ${./launcher/item-grammar.nix} "$out/share/haus/launcher/item-grammar.nix"

    cat > "$dir/read.nix" <<'EOF'
    # GENERATED by modules/desktop-check.nix — the argument-free entry point.
    source:
    (import ./show.nix {
      lib = import ./lib;
      registry = import ./registry.nix;
    }).read source
    EOF

    # The report script itself, beside the evaluator it drives. `haus show`
    # execs it from here; `nix run github:hausfold/haus#show` gets the same
    # file with the same directory baked in, which is what makes the CLI and a
    # publisher's CI the same command rather than two that agree today.
    install -Dm755 ${./core/haus-show.sh} "$out/share/haus/show.sh"

    # `haus desktop`'s no-argument listing needs the built-in names offline
    # and pinned to this same revision — the same argument as everything else
    # in this derivation, pointed at one more question. A plain JSON array,
    # not an evaluation the CLI would have to shell back out for.
    echo '${builtins.toJSON builtinDesktops}' > "$dir/desktops.json"
  ''
