#!/usr/bin/env bash
# focus — one switch for quiet, and the named states around it. Turns macOS Do
# Not Disturb on/off by pressing the symbolic hotkey nix-darwin declared (ID
# 175, ⌃⌥⇧⌘F13), sets/restores your Slack status, and runs any host hooks. The
# bar pill, the pounce palette command, and the CLI all drive this one script,
# so no two surfaces can ever disagree about what a toggle does.
#
# `focus 25` is the same switch with a fuse: quiet now, quiet off again in
# twenty-five minutes. What is stored is the until-timestamp, and what burns it
# down is a launchd one-shot — see the timer section for the one rule it obeys,
# which is the room's rule everywhere: it ends only the quiet it armed.
#
# `scene` is the same idea with more than one member: haus.focus.scenes.<name>
# declares a state (quiet · awake · an input device · apps · hooks) and this
# script enters and leaves it. `quiet` is the built-in one, which is why
# `focus scene quiet` is spelled as an alias of `focus on` rather than as a
# second copy of it — quiet's state IS the DND state, and reading it twice is
# how a pill starts lying.
#
# GENERATED by modules/focus/default.nix (@var@ substituted at build time).
set -uo pipefail

JQ="@jq@"
STATE_DIR="$HOME/.local/state/focus"
STATE_FILE="$STATE_DIR/state"
SCENE_FILE="$STATE_DIR/scene"
SCENE_PREV="$STATE_DIR/scene-prev.json"
SCENE_PID="$STATE_DIR/scene-caffeinate.pid"
# Bumped on every entry, by hand or by the daemon. The daemon remembers the id
# it entered under, so leaving and re-entering the SAME scene between two ticks
# is visible to it — otherwise ownership is tracked by name, an off-then-on
# inside one interval is invisible, and the daemon evicts a scene YOU entered.
SCENE_ENTRY="$STATE_DIR/scene-entry"
AUTO_STATE="$STATE_DIR/auto.json"
# `focus 25` — the until-timestamp, and the claim it is burning (see the timer
# section). QUIET_ENTRY is the same idea as SCENE_ENTRY one level down: every
# write of the quiet state bumps it, so a fuse can tell the quiet it armed from
# a quiet you turned off and on again while it slept.
TIMER_FILE="$STATE_DIR/timer.json"
QUIET_ENTRY="$STATE_DIR/quiet-entry"
SCENES="@scenes@"
SWITCH_AUDIO="@switchAudio@" # empty unless some scene names an input device

# ---- snug's bash painter, loaded only where a table is drawn ----------------
# `focus` is its own binary and inherits nobody's environment: the bar plugin,
# the pounce command and a person at a prompt all exec it directly, so the path
# is substituted at build time rather than inherited the way `haus show`
# inherits it from the `haus` wrapper. A caller's own HAUS_UI_SH still wins,
# so a working copy is one variable away.
#
# LAZY on purpose: the bar drives `focus` on a timer, and reading a thousand
# lines of bash on a path that prints one word is a cost paid every tick for
# nothing — only the two listings below call ui_load.
HAUS_UI_SH="${HAUS_UI_SH:-@uiSh@}"

# ── ui_load — source the painter once, and answer whether it can draw ────────
# The ONE copy of this block is modules/lib/ui-load.nix; `nix flake check`
# (ui-load-sync) diffs this file against it, so edit it THERE and re-copy.
# UI_READY=1 only when every verb named in UI_WANT arrived: the carrier sets
# UI_WANT to every ui_* verb it CALLS, not a sample, because a pin whose ui.sh
# predates one of them is a `command not found` halfway down a report — under
# `set -e` an abort AFTER the machine changed and before anything said so —
# and UI_READY would have licensed it. Idempotent, so calling it lazily from
# each draw path and calling it once at load are the same verb; a path that
# never draws never calls it and pays nothing. Three traps, each silent, each
# paid for before this block existed:
#
#   * ui.sh is bash 4+ (`declare -gA`, `${v^^}`). macOS's /bin/bash 3.2 does
#     not fail it quietly: three `bad substitution` errors and a half-loaded
#     painter that answers `type` and then draws nothing — so the version is
#     checked, never assumed, and 3.2 keeps the plain output.
#   * `|| true` is load-bearing under `set -euo pipefail`: a sourced file's
#     non-zero exit is the caller's to survive, and a ui.sh that failed at
#     load would otherwise abort the verb mid-flight — for `awake 3h`, AFTER
#     the assertion started.
#   * The path stays in `HAUS_UI_SH`, never `UI_SH` — that exact name is
#     ui.sh's own source-twice sentinel, and holding the path in it makes the
#     file return before defining anything, with no error and no colour.
UI_READY=""
ui_load() {
    [ -n "${UI_LOADED:-}" ] && return 0
    UI_LOADED=1
    [ "${BASH_VERSINFO[0]:-0}" -ge 4 ] || return 0
    if [ -r "${HAUS_UI_SH:-}" ]; then
        # shellcheck source=/dev/null
        source "$HAUS_UI_SH" || true
    fi
    [ -n "${UI_WANT:-}" ] || return 0
    # shellcheck disable=SC2086
    type $UI_WANT >/dev/null 2>&1 && UI_READY=1
    return 0
}
# Probed by the verbs the listings CALL; the plain columns are still there for
# a machine that fails the probe.
UI_WANT="ui_col ui_trow ui_table_data ui_table_clear"

# The trigger probes, each overridable the way modules/core/awake.sh does it —
# the suite (test/focus-auto.sh) stubs every one of them, which is how the
# decision logic below is tested on a machine that is not a Mac. Nothing else
# sets these.
DATE="${FOCUS_DATE_BIN:-/bin/date}"
PMSET="${FOCUS_PMSET_BIN:-/usr/bin/pmset}"
# Not probes: the two macOS binaries the timer and the DND leg act THROUGH.
# Overridable for the same reason the probes are — test/focus-timer.sh drives a
# whole arm-and-expire on a machine with neither, which is the only way the
# claim rule can be run rather than read. Nothing else sets them.
LAUNCHCTL="${FOCUS_LAUNCHCTL_BIN:-/bin/launchctl}"
OSASCRIPT="${FOCUS_OSASCRIPT_BIN:-/usr/bin/osascript}"
NETWORKSETUP="${FOCUS_NETWORKSETUP_BIN:-/usr/sbin/networksetup}"
SYSTEM_PROFILER="${FOCUS_SYSTEM_PROFILER_BIN:-/usr/sbin/system_profiler}"
# The displays room's helper, when this machine has it: one CGGetActiveDisplayList
# call, instant. Absent, the screen count falls back to system_profiler, which is
# correct and slow — a real second destination rather than a silent degrade, and
# the reason focus does NOT depend on that room.
HAUSDISP="${FOCUS_HAUSDISP_BIN:-/run/current-system/sw/bin/hausdisp}"
DB="$HOME/Library/DoNotDisturb/DB/Assertions.json"
# The one both-bars poke (modules/core/haus-bar-poke.sh). Addressed absolutely
# for the same reason `notify` below is: this runs under launchd, from the bar
# and from the palette, on a PATH that names nothing of ours. It knows where
# each bar binary landed — which is why this room no longer reads the roster at
# all — and is a no-op on a machine with no bar.
BAR_POKE="${FOCUS_BAR_POKE_BIN:-/run/current-system/sw/bin/haus-bar-poke}"

# Must match the AppleSymbolicHotKeys 175 binding written by default.nix.
KEY_CODE=@keyCode@
# The launchd job that sleeps out a `focus 25`. Substituted rather than typed
# here as well as in the agent, for the same reason the key code is: a label
# that does not match is a `kickstart` that silently starts nothing, and a fuse
# that never burns.
TIMER_LABEL=@timerLabel@

SLACK_ENABLED=@slackEnabled@
SLACK_TOKEN_CMD=@slackTokenCommand@
# What to tell somebody whose token is missing, which depends on WHO holds it:
# haus (an unset tokenCommand — the value is one `haus-secret --check` away) or
# the host's own command. Substituted rather than decided here, because only the
# module knows which shape is in force.
SLACK_TOKEN_HINT=@slackTokenHint@
SLACK_STATUS_TEXT=@slackStatusText@
SLACK_STATUS_EMOJI=@slackStatusEmoji@
SLACK_SNOOZE=@slackSnooze@
SLACK_SNOOZE_MINUTES=1440 # failsafe cap; turning it off ends it earlier
HOOKS=(@hooks@)

# The pounce the launcher room runs: the notarized release app straight from
# the store, whose team-anchored signature is what keeps its TCC grants alive
# across rebuilds. When it has the `focus` subcommand, focus rides its
# Accessibility + Full Disk Access grants for the press AND the state read —
# one pair of checkboxes covers every surface. Empty with the launcher room
# off (no daemon to forward to). The probe greps --help because an OLDER
# pounce treats unknown args as ClientMode and would open the palette; never
# call `focus` unprobed.
POUNCE_BIN=@pounceBin@
pounce_focus_available() {
    [ -n "$POUNCE_BIN" ] && [ -x "$POUNCE_BIN" ] && "$POUNCE_BIN" --help 2>/dev/null | grep -q "focus status"
}

note() { printf 'focus: %s\n' "$*" >&2; }
# Everything this desktop puts on screen goes through `haus-notify`: trill
# draws it when its daemon answers, macOS's own banner when it doesn't, and
# `~/.config/trill/rules.json` is where you route or silence it — matching on
# the `--source` below. It exits 0 whatever happens, so a missed banner can
# never be why this script failed.
#
# Addressed absolutely because this runs under launchd (the pounce daemon), whose
# PATH names nothing of ours. That path is
# `environment.systemPackages` — stable across rebuilds, the same reason
# `haus-activate` is reachable there.
notify() { /run/current-system/sw/bin/haus-notify --source haus.focus --title focus --body "$1" >/dev/null 2>&1 || true; }
poke_bar() {
    [ -x "$BAR_POKE" ] && "$BAR_POKE" focus_change >/dev/null 2>&1 || true
}

# on|off. Exact when the launcher's pounce can report it (its FDA grant) or when
# Assertions.json is readable directly (the calling app's own FDA); otherwise
# falls back to our own last write. Blind spots in fallback mode: toggles
# made from Control Center or another device.
focus_state() {
    local s db
    if pounce_focus_available; then
        s=$("$POUNCE_BIN" focus status 2>/dev/null) || s=""
        case "$s" in on | off)
            echo "$s"
            return
            ;;
        esac
    fi
    db=$(/bin/cat "$DB" 2>/dev/null || true)
    if [ -n "$db" ]; then
        if printf '%s' "$db" | "$JQ" -e '(.data[0].storeAssertionRecords // []) | length > 0' >/dev/null 2>&1; then
            echo on
        else
            echo off
        fi
        return
    fi
    /bin/cat "$STATE_FILE" 2>/dev/null || echo off
}

quiet_entry_id() {
    local n
    n=$(/bin/cat "$QUIET_ENTRY" 2>/dev/null || true)
    case "$n" in "" | *[!0-9]*) echo 0 ;; *) echo "$n" ;; esac
}

quiet_entry_bump() { printf '%s\n' "$(($(quiet_entry_id) + 1))" >"$QUIET_ENTRY"; }

# Press the DND chord. Preferred: `pounce focus toggle` — since pounce 0.4.3
# the CLI forwards the press to the resident daemon whenever the calling
# context lacks the grant (TCC checks the RESPONSIBLE process — sketchybar
# for the pill, your terminal for the CLI — never the pounce binary itself),
# so the one Accessibility checkbox on the launcher's Pounce.app covers every
# surface. Fallback: System Events — only without a focus-capable pounce;
# then the keystroke is attributed to the app that invoked focus.
press_hotkey() {
    if pounce_focus_available && "$POUNCE_BIN" focus toggle 2>/dev/null; then
        return 0
    fi
    "$OSASCRIPT" -e "tell application \"System Events\" to key code $KEY_CODE using {control down, option down, shift down, command down}" >/dev/null 2>&1
}

slack_token() { /bin/bash -c "$SLACK_TOKEN_CMD" 2>/dev/null || true; }

slack_api() { # $1 method, rest = curl args
    local method=$1
    shift
    /usr/bin/curl -sf --max-time 5 -H "Authorization: Bearer $TOK" "$@" \
        "https://slack.com/api/$method" 2>/dev/null
}

slack_set() { # $1 = on|off
    [ "$SLACK_ENABLED" = 1 ] || return 0
    TOK=$(slack_token)
    if [ -z "$TOK" ]; then
        note "slack: no token yet — skipping (see 'focus doctor')"
        return 0
    fi
    local prev="$STATE_DIR/slack-prev.json"
    if [ "$1" = on ]; then
        # Stash whatever status was there so turning it off can put it back —
        # but only when there is nothing stashed already. An existing stash means
        # the last `focus off` could not reach Slack and kept it (see the restore
        # arm below), so the status Slack is showing RIGHT NOW is the focus one:
        # re-stashing would record the focus status as the thing to return to and
        # make it stick forever, which is the exact failure the keeping was for.
        #
        # And it has to be tested before the capture rather than after, because a
        # `>"$prev"` redirect truncates at the moment the pipeline is set up, not
        # when jq writes — so an offline `focus on` would empty the kept stash
        # before anything downstream got a chance to notice.
        if [ ! -s "$prev" ]; then
            # Through a temp file for the same reason: nothing is allowed to
            # shorten $prev until we have a whole replacement in hand. jq writes
            # nothing and exits 0 on an empty body, and Slack answers HTTP 200
            # with {"ok":false,…} for an expired token — both produce a file that
            # is not a status, so the shape is checked before it becomes one.
            local tmp="$prev.tmp"
            if slack_api users.profile.get \
                | "$JQ" -e 'select(.ok == true)
                    | {profile:{status_text:(.profile.status_text // ""), status_emoji:(.profile.status_emoji // ""), status_expiration:0}}' \
                >"$tmp" 2>/dev/null && [ -s "$tmp" ]; then
                mv -f "$tmp" "$prev"
            else
                rm -f "$tmp" "$prev"
            fi
        fi
        local body
        body=$("$JQ" -n --arg t "$SLACK_STATUS_TEXT" --arg e "$SLACK_STATUS_EMOJI" \
            '{profile:{status_text:$t,status_emoji:$e,status_expiration:0}}')
        slack_api users.profile.set -H "Content-type: application/json; charset=utf-8" -d "$body" \
            | "$JQ" -e '.ok' >/dev/null || note "slack: users.profile.set failed"
        if [ "$SLACK_SNOOZE" = 1 ]; then
            slack_api dnd.setSnooze -d "num_minutes=$SLACK_SNOOZE_MINUTES" \
                | "$JQ" -e '.ok' >/dev/null || note "slack: dnd.setSnooze failed"
        fi
    else
        if [ -s "$prev" ]; then
            # Keep the stash when the restore did not land. Slack is a network
            # call and leaving Focus is exactly when it can be missing (a train,
            # a hotel portal, Wi-Fi off) — and the old unconditional `rm` threw
            # away the ONLY record of the status you had before Focus, so the
            # next successful toggle had nothing to put back and your Slack
            # status stayed stuck on the focus one. Now the next `focus off`
            # with a network retries it.
            if slack_api users.profile.set -H "Content-type: application/json; charset=utf-8" -d @"$prev" \
                | "$JQ" -e '.ok' >/dev/null; then
                rm -f "$prev"
            else
                note "slack: status restore failed — keeping the stash, retried on the next 'focus off'"
            fi
        else
            slack_api users.profile.set -H "Content-type: application/json; charset=utf-8" \
                -d '{"profile":{"status_text":"","status_emoji":""}}' \
                | "$JQ" -e '.ok' >/dev/null || note "slack: status clear failed"
        fi
        if [ "$SLACK_SNOOZE" = 1 ]; then
            slack_api dnd.endSnooze -X POST | "$JQ" -e '.ok' >/dev/null || true
        fi
    fi
}

run_hooks() { # $1 = on|off
    local h
    for h in ${HOOKS[@]+"${HOOKS[@]}"}; do
        "$h" "$1" || note "hook failed (non-fatal): $h"
    done
}

apply() { # $1 = on|off
    local want=$1 cur
    cur=$(focus_state)
    if [ "$cur" != "$want" ]; then
        if ! press_hotkey; then
            note "keypress failed — the app invoking focus needs an Accessibility grant (run 'focus doctor')"
            notify "No Accessibility grant — run 'focus doctor' in a terminal"
            exit 1
        fi
    fi
    /bin/mkdir -p "$STATE_DIR"
    printf '%s\n' "$want" >"$STATE_FILE"
    # Every write of the quiet state is a new quiet, and the counter is how a
    # timer tells one from the next: a fuse armed under 7 and reaching expiry at
    # 8 is looking at a quiet somebody else chose. Bumped on the way OFF too —
    # off-then-on inside one fuse is exactly the sequence the claim has to see.
    quiet_entry_bump
    slack_set "$want"
    run_hooks "$want"
    poke_bar
    note "$want"
}

# ---- scenes ----------------------------------------------------------------
# A scene is data (@scenes@ is a JSON file the module wrote), never generated
# shell — so nothing a desktop or a host writes into a scene can become code
# here. Exactly one scene is active at a time; the name lives in $SCENE_FILE
# and what it displaced lives in $SCENE_PREV.

scene_exists() { "$JQ" -e --arg n "$1" 'has($n)' "$SCENES" >/dev/null 2>&1; }
# `// empty` also swallows a literal `false`, so every boolean field here reads
# as "" when it is off. Test for `= true`, never for `= false`.
scene_field() { "$JQ" -r --arg n "$1" ".[\$n]$2 // empty" "$SCENES" 2>/dev/null; }
scene_names() { "$JQ" -r 'keys[]' "$SCENES" 2>/dev/null; }

# The scene that is on, or "off". It can name a scene the host has since
# deleted from the table, which is exactly why LEAVING one is driven entirely
# off $SCENE_PREV (what the scene displaced) and never off the table: a rebuild
# between entering and leaving must not strand the Mac quiet and on the wrong
# microphone with nothing left that knows to put them back.
scene_active() {
    local s
    s=$(/bin/cat "$SCENE_FILE" 2>/dev/null || true)
    [ -n "$s" ] && echo "$s" || echo off
}

scene_entry_id() {
    local n
    n=$(/bin/cat "$SCENE_ENTRY" 2>/dev/null || true)
    case "$n" in "" | *[!0-9]*) echo 0 ;; *) echo "$n" ;; esac
}

scene_entry_bump() { printf '%s\n' "$(($(scene_entry_id) + 1))" >"$SCENE_ENTRY"; }

audio_input_get() {
    [ -n "$SWITCH_AUDIO" ] || return 0
    "$SWITCH_AUDIO" -c -t input 2>/dev/null || true
}

audio_input_set() { # $1 = exact device name
    [ -n "$SWITCH_AUDIO" ] || return 0
    "$SWITCH_AUDIO" -t input -s "$1" >/dev/null 2>&1 \
        || note "audio: no input device named \"$1\" — left as it was"
}

# An app is named the way `open -a` takes it — a name, a bundle id, or a path —
# and AppleScript has two references to reach one, so both are TRIED rather than
# guessed at from the shape of the string: a bundle id and a dotted app name
# (`draw.io`) look identical, and a heuristic that picks wrong makes closeOnExit
# silently do nothing. `application id` first because it is the exact one; the
# name form answers `false` for anything macOS doesn't know, so an app that
# exists under neither reads as "not running", which is right.
#
# The name reaches osascript as an ARGUMENT, never spliced into the script text:
# scene data stays data, which is the whole reason the table is JSON the engine
# reads rather than generated shell.
#
# `application X is running` is the one form that answers without launching what
# it asks about — `tell application X to ...` would start it.
app_running() { # $1 = app name, bundle id or path
    "$OSASCRIPT" - "$1" <<'EOS' 2>/dev/null | grep -q true
on run argv
    set a to item 1 of argv
    try
        return (application id a is running)
    end try
    return (application a is running)
end run
EOS
}

# The polite quit — the same message ⌘Q sends, so an app with unsaved work still
# gets to put its save sheet up. `ignoring application responses` is what makes
# that safe to do from here: without it osascript waits for the reply, and an
# app showing a sheet doesn't reply until a person dismisses it (or the Apple
# event times out, two minutes later), which would leave the rest of the exit —
# the caffeinate hold, the microphone, the state files — hanging behind a modal.
# ⌘Q from the Dock doesn't wait either. Guarded by `is running` so quitting what
# is already gone can never be what starts it.
app_quit() { # $1 = app name, bundle id or path
    "$OSASCRIPT" - "$1" <<'EOS' >/dev/null 2>&1
on run argv
    set a to item 1 of argv
    try
        if application id a is running then
            ignoring application responses
                tell application id a to quit
            end ignoring
        end if
        return
    end try
    if application a is running then
        ignoring application responses
            tell application a to quit
        end ignoring
    end if
end run
EOS
}

# caffeinate outlives this script on purpose (the scene is what holds the
# assertion, not the command that started it). The pid file survives a reboot
# and pids get reused, so releasing checks it is still caffeinate before
# signalling anything.
sleep_hold() {
    sleep_release
    # Detached from this script's stdout/stderr as well as its lifetime, or a
    # caller that captures output (`out=$(focus scene x)`) blocks until the
    # assertion is released.
    /usr/bin/caffeinate -dimsu >/dev/null 2>&1 &
    printf '%s\n' "$!" >"$SCENE_PID"
}

sleep_release() {
    local pid comm
    pid=$(/bin/cat "$SCENE_PID" 2>/dev/null || true)
    if [ -n "$pid" ]; then
        comm=$(/bin/ps -o comm= -p "$pid" 2>/dev/null || true)
        case "$comm" in *caffeinate) /bin/kill "$pid" 2>/dev/null ;; esac
    fi
    /bin/rm -f "$SCENE_PID"
}

# `</dev/null` on every hook and every `open`: the loop's own stdin is the
# process substitution holding the rest of the list, and a hook that reads
# stdin would swallow its successors.
scene_hooks() { # $1 = scene, $2 = on|off
    local h
    while IFS= read -r h; do
        [ -n "$h" ] || continue
        "$h" "$2" </dev/null || note "hook failed (non-fatal): $h"
    done < <(scene_field "$1" '.hooks[]?')
}

# What a scene displaced, written on entry and read on exit. `prev` records the
# world as it was; `took` records which levers this scene actually pulled, so
# leaving reverses exactly those and nothing else — and can do it without the
# scene still existing in the table.
scene_prev_write() { # $1 = sceneDnd, $2 = tookDnd, $3 = tookAudio, $4 = restore
    "$JQ" -n \
        --arg dnd "$(focus_state)" --arg audio "$(audio_input_get)" \
        --argjson sceneDnd "$1" --argjson tookDnd "$2" \
        --argjson tookAudio "$3" --argjson restore "$4" \
        '{dnd:$dnd,audioInput:$audio,sceneDnd:$sceneDnd,tookDnd:$tookDnd,tookAudio:$tookAudio,restore:$restore}' \
        >"$SCENE_PREV" 2>/dev/null || /bin/rm -f "$SCENE_PREV"
}

scene_prev_read() { "$JQ" -r "$1 // empty" "$SCENE_PREV" 2>/dev/null; }

# A second write, because which apps an entry STARTED is only known after it has
# started them — and `prev` has to exist before the DND leg, which can exit. A
# scene that doesn't close its apps writes nothing here, so exit finds no list
# and quits nothing.
scene_prev_took_apps() { # $1 = JSON array of apps this entry launched
    local merged
    merged=$("$JQ" --argjson a "$1" '.tookApps = $a' "$SCENE_PREV" 2>/dev/null) || return 0
    printf '%s\n' "$merged" >"$SCENE_PREV"
}

scene_enter() {
    local name=$1 active
    # `quiet` is the built-in and is not in the table: it is what focus on/off,
    # the pill and the palette command already do.
    if [ "$name" = quiet ]; then
        active=$(scene_active)
        [ "$active" != off ] && scene_off
        apply on
        return
    fi
    if ! scene_exists "$name"; then
        note "no scene named \"$name\""
        scene_list >&2
        exit 64
    fi
    active=$(scene_active)
    if [ "$active" = "$name" ]; then
        note "$name (already)"
        return
    fi
    [ "$active" != off ] && scene_off

    local sceneDnd wantAudio takeDnd takeAudio restore app
    sceneDnd=$([ "$(scene_field "$name" .dnd)" = true ] && echo true || echo false)
    restore=$([ "$(scene_field "$name" .restorePreviousState)" = true ] && echo true || echo false)
    wantAudio=$(scene_field "$name" .audioInput)

    # A scene only TAKES a lever it actually moves. Entering a quiet scene while
    # already quiet must not re-run the Slack leg — `slack_set on` would stash
    # the current (already-quiet) status as the one to restore, and that lie
    # survives until the next un-quiet.
    takeDnd=false
    [ "$sceneDnd" = true ] && [ "$(focus_state)" != on ] && takeDnd=true
    takeAudio=false
    [ -n "$wantAudio" ] && [ "$wantAudio" != "$(audio_input_get)" ] && takeAudio=true

    /bin/mkdir -p "$STATE_DIR"
    scene_prev_write "$sceneDnd" "$takeDnd" "$takeAudio" "$restore"

    # The DND leg first, and the name written only after it: `apply` exits when
    # the keypress has no Accessibility grant, and a scene recorded as ON while
    # nothing about the machine changed is the one failure that outlives the
    # command.
    [ "$takeDnd" = true ] && apply on
    printf '%s\n' "$name" >"$SCENE_FILE"
    scene_entry_bump

    [ "$(scene_field "$name" .preventSleep)" = true ] && sleep_hold
    [ "$takeAudio" = true ] && audio_input_set "$wantAudio"

    # Only what this scene actually STARTED is its to close: an app you already
    # had open is not a lever it pulled, the same rule takeDnd and takeAudio
    # follow above. The probe costs an osascript per app, so it is only paid by
    # a scene that asked to close them.
    local closeApps took started
    closeApps=$([ "$(scene_field "$name" .closeApps)" = true ] && echo true || echo false)
    took='[]'
    while IFS= read -r app; do
        [ -n "$app" ] || continue
        started=false
        if [ "$closeApps" = true ] && ! app_running "$app"; then started=true; fi
        if ! /usr/bin/open -a "$app" </dev/null >/dev/null 2>&1; then
            note "could not open \"$app\""
        elif [ "$started" = true ]; then
            took=$("$JQ" -n --argjson t "$took" --arg a "$app" '$t + [$a]')
        fi
    done < <(scene_field "$name" '.apps[]?')
    if [ "$closeApps" = true ]; then scene_prev_took_apps "$took"; fi

    scene_hooks "$name" on
    poke_bar
    note "scene $name"
}

# Leave whatever is on, reversing only the levers the scene took. With no scene
# active this un-quiets, so `focus scene off` means "back to normal" whether or
# not a scene was involved — one thing to remember instead of two.
scene_off() {
    local name
    name=$(scene_active)
    if [ "$name" = off ]; then
        [ "$(focus_state)" = on ] && apply off
        return
    fi

    # Read off `prev` like every other reversal — never off the table — so a
    # scene the host deleted mid-flight still closes what it opened. Read HERE
    # and quit at the very end: the levers below all read this same file, and an
    # app is the one thing on the list that can put a dialog between us and them.
    local quitApps
    quitApps=$("$JQ" -r '.tookApps[]? // empty' "$SCENE_PREV" 2>/dev/null)

    scene_hooks "$name" off
    sleep_release

    [ "$(scene_prev_read .tookAudio)" = true ] && audio_input_set "$(scene_prev_read .audioInput)"

    # Un-quiet in two cases and no others: this scene is what made the Mac
    # quiet, or the scene asserts quiet and the host said not to put the
    # previous state back — which is the whole job `restorePreviousState = false`
    # has, and the only way leaving can un-quiet a Mac that was already quiet.
    # No prev file at all (the entry's write failed, or state was hand-edited)
    # means the levers are unknown — and "unknown" has to resolve to the state a
    # person can get back out of, which is not-quiet.
    if [ ! -f "$SCENE_PREV" ]; then
        [ "$(focus_state)" = on ] && apply off
    elif [ "$(scene_prev_read .tookDnd)" = true ] ||
        { [ "$(scene_prev_read .sceneDnd)" = true ] && [ "$(scene_prev_read .restore)" != true ]; }; then
        apply off
    fi

    /bin/rm -f "$SCENE_FILE" "$SCENE_PREV"
    poke_bar

    # Last, with the scene already recorded as off and the bar already repainted:
    # the quit is asynchronous but an app can still take a visible moment to go,
    # and a pill that waits for OBS to finish closing is a pill that looks dead
    # to the second click — which would run this whole function again, against a
    # `prev` file the first pass has since removed.
    while IFS= read -r app; do
        [ -n "$app" ] || continue
        app_quit "$app"
    done <<<"$quitApps"

    note "scene off ($name)"
}

# The verb a KEY spends. `haus.focus.scenes.<name>.key` binds one leader key to
# one scene, and a key has no room for a second half, so it has to mean both
# directions: press to enter, press again to leave. Every other surface already
# carries its own way back — the palette puts Leave Scene beside every row, the
# pill has its click — and a key that could only ever enter would be the one
# that lies about what it does on the second press.
#
# Read through `scene_status`, not `scene_active`: quiet is the built-in scene
# and is not in the table, so `scene_active` answers `off` while the Mac is
# quiet, and `focus scene toggle quiet` would quieten an already-quiet Mac
# forever. Leaving is `scene_off`'s whole job, a scene `focus auto` entered
# included — the daemon loses every argument the moment a person takes one.
scene_toggle() {
    local name=$1
    if [ -z "$name" ]; then
        echo "usage: focus scene toggle <name>" >&2
        exit 64
    fi
    if [ "$(scene_status)" = "$name" ]; then
        scene_off
    else
        scene_enter "$name"
    fi
}

scene_status() {
    local name
    name=$(scene_active)
    if [ "$name" != off ]; then
        echo "$name"
    elif [ "$(focus_state)" = on ]; then
        echo quiet
    else
        echo off
    fi
}

scene_list() {
    local now name desc
    now=$(scene_status)
    ui_load
    printf 'scenes (* = on):\n'
    if [ -n "$UI_READY" ]; then
        ui_table_clear
        # The `*` is a column, not a prefix: a name lands in the same place
        # whether or not it is the one that is on, which is what makes the list
        # scannable. `never` — a one-cell mark is right or it is absent.
        ui_col on   1 1 ok      never
        ui_col scene 6 2 subject right
        ui_col what  8 5 muted   right
        ui_trow "$([ "$now" = quiet ] && echo '*' || echo '')" quiet \
            "the built-in — what focus on/off, the pill and the palette enter"
        while IFS= read -r name; do
            [ -n "$name" ] || continue
            desc=$(scene_field "$name" .description)
            ui_trow "$([ "$now" = "$name" ] && echo '*' || echo '')" "$name" "$desc"
        done < <(scene_names)
        ui_table_data 2
        return 0
    fi
    printf '  %s %-14s %s\n' "$([ "$now" = quiet ] && echo '*' || echo ' ')" quiet \
        "the built-in — what focus on/off, the pill and the palette enter"
    while IFS= read -r name; do
        [ -n "$name" ] || continue
        desc=$(scene_field "$name" .description)
        printf '  %s %-14s %s\n' "$([ "$now" = "$name" ] && echo '*' || echo ' ')" "$name" "$desc"
    done < <(scene_names)
}

# ---- the timer -------------------------------------------------------------
# `focus 25` is quiet with a fuse on it. What is written down is the
# UNTIL-TIMESTAMP, never the sleeping process: a logout, a reboot or a rebuild
# takes the process and leaves the fact, and the agent's RunAtLoad picks the
# file back up with whatever is left of it.
#
# A fuse is a CLAIM on the quiet it armed, and it burns only while that claim
# stands — the same "reverse only the lever you pulled" rule the scene engine
# and the trigger daemon each follow, one level down. `timer_claim` is the
# whole of it, and every one of its three questions is a way to be void:
#
#   * THE QUIET COUNTER MOVED. Every write of the quiet state bumps it, so a
#     quiet you switched off and on again while the fuse slept is a different
#     quiet — one you chose, which nothing here may end. This is the case the
#     feature would otherwise get wrong, and it is the reason the counter
#     exists: without it, `focus 25` followed by two hand toggles un-quiets you
#     twenty minutes later for no reason you could name.
#   * THE MAC IS NO LONGER QUIET. Nothing left to end.
#   * A SCENE IS ON. A scene owns the whole state while it runs, so un-quieting
#     underneath it would leave the pill saying one thing and the caffeinate
#     hold, the microphone and the apps saying another. Arming refuses while a
#     scene is on for the same reason; this catches one entered afterwards.
#
# Void always resolves to "forget the fuse", never to "act anyway" — a fuse
# that cannot prove what it is burning has nothing to burn. It also resolves
# the file: `timer_claim` deletes it on the way out, so a dead fuse cannot keep
# counting down on the bar.

now() {
    if [ -n "${FOCUS_NOW:-}" ]; then
        printf '%s\n' "$FOCUS_NOW"
    else
        "$DATE" +%s
    fi
}

timer_read() { "$JQ" -r "$1 // empty" "$TIMER_FILE" 2>/dev/null; }

# `focus 25` — a bare number is MINUTES here, where `awake 3` is hours. Each
# verb takes the unit it is actually used in: quiet is a stretch of work,
# awake is an afternoon. `25m`, `90m` and `1h` are spelled out either way, so
# only the bare form differs, and only the usage text can say so.
#
# Capped at a day, because past that you want a scene: a state that outlives
# the sitting has apps, a microphone and a name, and `haus.focus.scenes` is
# where those live. The cap is also Slack's own snooze ceiling, so a fuse can
# never outlast the snooze it set.
parse_minutes() { # $1 = 25 | 25m | 90min | 1h — prints seconds, or fails
    local value=$1 amount unit=m
    case "$value" in
        *minutes) amount=${value%minutes} ;;
        *minute) amount=${value%minute} ;;
        *mins) amount=${value%mins} ;;
        *min) amount=${value%min} ;;
        *hours)
            amount=${value%hours}
            unit=h
            ;;
        *hour)
            amount=${value%hour}
            unit=h
            ;;
        *hrs)
            amount=${value%hrs}
            unit=h
            ;;
        *hr)
            amount=${value%hr}
            unit=h
            ;;
        *m) amount=${value%m} ;;
        *h)
            amount=${value%h}
            unit=h
            ;;
        *) amount=$value ;;
    esac
    # 10#, or `09` reads as octal — the same trap win_minutes carries below.
    case "$amount" in '' | *[!0-9]*) return 1 ;; esac
    amount=$((10#$amount))
    [ "$amount" -gt 0 ] || return 1
    if [ "$unit" = h ]; then
        [ "$amount" -le 24 ] || return 1
        printf '%s\n' "$((amount * 3600))"
    else
        [ "$amount" -le 1440 ] || return 1
        printf '%s\n' "$((amount * 60))"
    fi
}

# Rounded UP to the next minute: "1m" through the final minute is the honest
# thing for a pill to say, where "0m" reads as finished for sixty seconds. Same
# rounding `awake` uses, and the pill's own label is formatted from the raw
# seconds so the two can differ in width without differing in meaning.
format_remaining() { # $1 = seconds
    local minutes=$((($1 + 59) / 60)) hours
    hours=$((minutes / 60))
    minutes=$((minutes % 60))
    if [ "$hours" -gt 0 ]; then
        printf '%dh %02dm\n' "$hours" "$minutes"
    else
        printf '%dm\n' "$minutes"
    fi
}

# Does the fuse still own the quiet it armed? Answers no by deleting it, which
# is the self-heal that keeps a dead fuse off the pill without anything having
# to run on a timer to sweep it. Says nothing about the CLOCK — expiry is the
# caller's question and this one is only about the claim.
timer_claim() {
    local entry
    [ -f "$TIMER_FILE" ] || return 1
    entry=$(timer_read .entry)
    case "$(timer_read .until)" in "" | *[!0-9]*) entry="" ;; esac
    if [ -z "$entry" ] || [ "$entry" != "$(quiet_entry_id)" ] \
        || [ "$(scene_active)" != off ] || [ "$(focus_state)" != on ]; then
        /bin/rm -f "$TIMER_FILE"
        return 1
    fi
    return 0
}

# Seconds left, or nothing at all — for a void fuse, for no fuse, and for one
# whose moment has come and gone while the agent is still waking up. All three
# read the same to a pill, and correctly so: there is no countdown to draw.
timer_remaining() {
    local until current
    timer_claim || return 0
    until=$(timer_read .until)
    current=$(now)
    [ "$until" -gt "$current" ] && printf '%s\n' "$((until - current))"
    return 0
}

timer_domain() { printf 'gui/%s/%s\n' "$(/usr/bin/id -u)" "$TIMER_LABEL"; }

# Drop the fuse and leave the quiet alone. The counter already voids a fuse the
# moment anything writes the quiet state, so this is the tidying half: it takes
# the file off the pill and the sleeping agent out of the process list in the
# same breath, rather than leaving a job to wake at 14:35 and find nothing to do.
timer_cancel() {
    [ -f "$TIMER_FILE" ] || return 0
    /bin/rm -f "$TIMER_FILE"
    "$LAUNCHCTL" kill TERM "$(timer_domain)" >/dev/null 2>&1 || true
}

timer_arm() { # $1 = seconds
    local seconds=$1 until token at
    if [ "$(scene_active)" != off ]; then
        note "a scene is on — 'focus scene off' first, or give that scene a when.time window"
        exit 1
    fi
    # Not `apply on` unconditionally: on an already-quiet Mac that would re-run
    # the Slack leg and the hooks for a quiet that never changed, which is the
    # same edge-pairing rule `takeDnd` keeps for scenes. Arming over a quiet you
    # set by hand is still a fuse — you asked for one — it is just not a second
    # entry into a state you are already in.
    [ "$(focus_state)" = on ] || apply on
    /bin/mkdir -p "$STATE_DIR"
    # AFTER the apply, so the id recorded below is the one that write produced.
    # On an already-quiet Mac this bump is the only one, and it is what makes
    # the fuse's claim specific rather than "whatever quiet is on at 14:35".
    quiet_entry_bump
    until=$(($(now) + seconds))
    token="$until-$$-${RANDOM:-0}"
    if ! "$JQ" -n --arg t "$token" --argjson u "$until" --argjson e "$(quiet_entry_id)" \
        '{token:$t,until:$u,entry:$e}' >"$TIMER_FILE" 2>/dev/null; then
        /bin/rm -f "$TIMER_FILE"
        note "could not write the timer — quiet is on; 'focus off' ends it"
        exit 1
    fi
    # `-k` restarts a job that is already sleeping on an older fuse, so a second
    # `focus 25` replaces the first rather than racing it.
    if ! "$LAUNCHCTL" kickstart -k "$(timer_domain)" >/dev/null 2>&1; then
        /bin/rm -f "$TIMER_FILE"
        note "could not start $TIMER_LABEL — rebuild once so its launchd job is loaded."
        note "quiet is on and will stay on; 'focus off' ends it"
        exit 1
    fi
    poke_bar
    at=$("$DATE" -r "$until" '+%H:%M' 2>/dev/null || true)
    note "quiet for $(format_remaining "$seconds")${at:+ (until $at)}"
}

timer_status() {
    local left
    left=$(timer_remaining)
    if [ -z "$left" ]; then
        printf 'no timer\n'
    else
        printf 'quiet for %s more\n' "$(format_remaining "$left")"
    fi
}

# The fuse burning down. Ordered the way the trigger daemon orders its own
# edge: the file goes FIRST and the state changes after it. `apply` exits 1
# when the DND keypress has no Accessibility grant, and a fuse still on disk
# after that failure would be retried by the agent's next RunAtLoad — one
# failed un-quiet per login, forever. One attempt per fuse is the right number:
# the failure is still visible, and it happens once.
timer_fire() { # $1 = the token this run armed under
    [ "$(timer_read .token)" = "$1" ] || return 0
    timer_claim || return 0
    /bin/rm -f "$TIMER_FILE"
    apply off
    notify "Quiet is off — the timer ran out"
}

# The launchd one-shot behind `focus 25`. It sleeps out what is left of the
# fuse and then fires it.
#
# A LOOP rather than one sleep, because the clock and the sleep disagree across
# a lid close: a Mac that suspends for an hour mid-fuse comes back with the
# sleep either finished early or not finished at all, and only the timestamp
# knows which. Re-reading the clock after every wait makes both cases the same
# case — and a fuse whose moment passed while the Mac was shut fires on the way
# back up rather than at 3am tomorrow.
timer_run() {
    local until token current remaining child=0
    [ -f "$TIMER_FILE" ] || exit 0
    until=$(timer_read .until)
    token=$(timer_read .token)
    case "$until" in "" | *[!0-9]*)
        /bin/rm -f "$TIMER_FILE"
        exit 0
        ;;
    esac
    while :; do
        current=$(now)
        remaining=$((until - current))
        [ "$remaining" -gt 0 ] || break
        /bin/sleep "$remaining" &
        child=$!
        # A TERM from `timer_cancel` or from a replacing `kickstart -k` means
        # the fuse is gone: take the sleep down with us and change nothing.
        trap 'if [ "$child" -gt 0 ]; then /bin/kill "$child" 2>/dev/null || true; fi; exit 0' TERM INT HUP
        wait "$child" || true
        child=0
    done
    timer_fire "$token"
}

# ---- triggers --------------------------------------------------------------
# The half that enters a scene for you. Everything above is driven by a person;
# `focus auto` is one launchd tick asking each scene's `when` whether it holds
# right now, and it obeys exactly one rule: IT NEVER OVERRIDES A STATE YOU CHOSE.
#
# Three mechanics carry that rule, and each is here rather than in the option
# text because each is a decision that had a plausible other answer:
#
#   1. ENTRY IS EDGE-TRIGGERED. A scene is entered on the tick where its
#      condition turns true, never because it is still true. That is the whole
#      reason walking out of an auto-entered scene works: the condition holds,
#      no edge, nothing re-enters it. Level-triggering would re-enter it 30
#      seconds later and there would be no way to say no short of a rebuild.
#   2. ENTRY IS ONLY FROM NEUTRAL — no scene on, not quiet. A scene you entered
#      by hand, or a quiet you switched on, is an opinion; the daemon fills in
#      from nothing and otherwise waits. The edge is spent either way, so it
#      does not pounce the moment you go neutral.
#   3. IT LEAVES ONLY WHAT IT ENTERED, tracked as `owner` — the same "reverse
#      only the levers you pulled" rule the scene engine already follows, one
#      level up. The moment what's active isn't the owner, the daemon has
#      nothing to reverse and says so by forgetting it.

now_hhmm() { "$DATE" +%H%M; }
# LC_ALL=C, or a machine whose LANG is set gets `lun`/`mi`/`月` here and every
# `when.days` silently stops matching the enum — a trigger that degrades to
# silence, which is the failure this room asserts against elsewhere. launchd
# usually hands the daemon a C locale and a terminal usually doesn't, so without
# this `focus auto --probe` and the daemon could also disagree.
now_day() { LC_ALL=C "$DATE" +%a | /usr/bin/tr '[:upper:]' '[:lower:]'; }

win_minutes() { # HH:MM → minutes since midnight. 10# or `09` reads as octal.
    local h=${1%%:*} m=${1##*:}
    printf '%s\n' "$((10#$h * 60 + 10#$m))"
}

# Half-open [start,end): a 09:00-17:00 window is over AT 17:00, not a minute
# later, and an end earlier than the start wraps midnight (22:00-06:00 is one
# night). A window whose ends are equal can never hold, which is why the module
# asserts against it rather than letting it degrade to silence.
time_in_window() { # $1 = HH:MM-HH:MM, $2 = HHMM now
    local start end now
    start=$(win_minutes "${1%%-*}")
    end=$(win_minutes "${1##*-}")
    now=$((10#${2:0:2} * 60 + 10#${2:2:2}))
    if [ "$start" -le "$end" ]; then
        [ "$now" -ge "$start" ] && [ "$now" -lt "$end" ]
    else
        [ "$now" -ge "$start" ] || [ "$now" -lt "$end" ]
    fi
}

# ---- the probes, one reader each -------------------------------------------
# Every one of them answers "" for "I could not tell", and "" matches nothing:
# a condition whose fact is unknown does not hold. That is the conservative
# direction — an unreadable SSID leaves you where you are instead of entering a
# scene on a guess — and it is why `--probe` and `doctor` both print the raw
# reads, since "no match" and "no answer" look identical from the outside.

read_power() {
    case "$("$PMSET" -g batt 2>/dev/null)" in
        *"'AC Power'"*) echo ac ;;
        *"'Battery Power'"*) echo battery ;;
    esac
}

# `networksetup -getairportnetwork <device>` is the supported read, and the
# device is whatever this Mac calls its Wi-Fi port (en0 on most, en1 on some) —
# so it is looked up rather than assumed. macOS can refuse the SSID (Location
# Services), and it refuses by answering "You are not associated with an AirPort
# network", which is indistinguishable from being on none. Hence "" and a doctor
# line, never a guess.
read_wifi() {
    local dev out
    dev=$("$NETWORKSETUP" -listallhardwareports 2>/dev/null \
        | /usr/bin/awk '/^Hardware Port: Wi-Fi$/ { getline; print $2; exit }')
    [ -n "$dev" ] || return 0
    out=$("$NETWORKSETUP" -getairportnetwork "$dev" 2>/dev/null) || return 0
    case "$out" in
        "Current Wi-Fi Network: "*) printf '%s\n' "${out#Current Wi-Fi Network: }" ;;
    esac
}

# Two destinations, both real: the displays room's helper when this machine has
# it (one CGGetActiveDisplayList call), and system_profiler when it doesn't
# (correct, and slow enough to notice — which is what `triggers.interval`'s
# description tells you to raise the interval for).
read_displays() {
    local out n
    if [ -x "$HAUSDISP" ]; then
        out=$("$HAUSDISP" list 2>/dev/null | /usr/bin/head -1)
        case "$out" in
            "active displays: "*)
                printf '%s\n' "${out#active displays: }"
                return
                ;;
        esac
    fi
    n=$("$SYSTEM_PROFILER" -json SPDisplaysDataType 2>/dev/null \
        | "$JQ" '[.SPDisplaysDataType[]?.spdisplays_ndrvs[]?] | length' 2>/dev/null) || return 0
    case "$n" in "" | 0) return 0 ;; esac
    printf '%s\n' "$n"
}

# Does ANY scene ask about this fact? A probe nobody's condition names is never
# run — the same rule that keeps switchaudio-osx out of the closure until a
# scene names an input device, one layer up at runtime.
fact_wanted() { # $1 = power|wifi|displays
    case "$1" in
        power) "$JQ" -e 'any(.[]?; (.when.power // "any") != "any")' "$SCENES" >/dev/null 2>&1 ;;
        wifi) "$JQ" -e 'any(.[]?; ((.when.wifi // []) | length) > 0)' "$SCENES" >/dev/null 2>&1 ;;
        displays) "$JQ" -e 'any(.[]?; (.when.displays // null) != null)' "$SCENES" >/dev/null 2>&1 ;;
    esac
}

# Read once per tick, into globals, because `scene_matches` runs per scene and a
# probe in a command substitution can't memoize (the subshell keeps the cache).
# Six scenes must not mean six `system_profiler` runs.
FACT_HHMM=""
FACT_DAY=""
FACT_POWER=""
FACT_WIFI=""
FACT_DISPLAYS=""

probe_facts() {
    FACT_HHMM=$(now_hhmm)
    FACT_DAY=$(now_day)
    FACT_POWER=""
    FACT_WIFI=""
    FACT_DISPLAYS=""
    fact_wanted power && FACT_POWER=$(read_power)
    fact_wanted wifi && FACT_WIFI=$(read_wifi)
    fact_wanted displays && FACT_DISPLAYS=$(read_displays)
    return 0
}

scene_has_when() { # a scene with no condition is entered by a person and nothing else
    "$JQ" -e --arg n "$1" '
        (.[$n].when // {}) as $w
        | ($w.time // "") != ""
            or (($w.days // []) | length) > 0
            or (($w.wifi // []) | length) > 0
            or ($w.power // "any") != "any"
            or ($w.displays // null) != null
    ' "$SCENES" >/dev/null 2>&1
}

# Every condition a scene declares has to hold — they are ANDed, and a scene
# that declares none never matches at all. Reads the facts `probe_facts` took,
# so a whole tick sees ONE consistent picture of the machine.
#
# THREE answers, not two, and the third is why a scene doesn't flap:
#   0  holds
#   1  definitely does not hold — a probe answered, and the answer fails
#   2  cannot say — a probe returned nothing at all
# "Cannot say" is not "no". `networksetup` reports no network during sleep/wake,
# AP roaming and VPN reconnects, and CGGetActiveDisplayList under-counts while
# monitors re-negotiate on wake — which launchd's StartInterval lands right on
# top of. Treating that as a falling edge would leave the scene and then re-enter
# it a tick later: hooks off/on, the caffeinate hold dropped and retaken, DND and
# the Slack status flipped twice, and with `apps.closeOnExit` the apps QUIT AND
# RELAUNCHED — OBS, mid-recording, on the room's own example scene. So entering
# needs a 0 and leaving needs a 1, and an unknown holds everything where it is.
scene_matches() { # $1 = scene name; 0 = holds · 1 = does not · 2 = cannot say
    local name=$1 window days power displays wifi unknown=0
    scene_has_when "$name" || return 1

    window=$(scene_field "$name" .when.time)
    if [ -n "$window" ]; then
        time_in_window "$window" "$FACT_HHMM" || return 1
    fi

    days=$(scene_field "$name" '.when.days[]?')
    if [ -n "$days" ]; then
        printf '%s\n' "$days" | /usr/bin/grep -qxF "$FACT_DAY" || return 1
    fi

    # A definite no wins over an unknown, which is what the early `return 1`s
    # give: a scene wanting AC power and this network, off the wall with the
    # SSID unreadable, definitely does not hold.
    power=$(scene_field "$name" .when.power)
    if [ -n "$power" ] && [ "$power" != any ]; then
        if [ -z "$FACT_POWER" ]; then
            unknown=1
        elif [ "$power" != "$FACT_POWER" ]; then
            return 1
        fi
    fi

    wifi=$(scene_field "$name" '.when.wifi[]?')
    if [ -n "$wifi" ]; then
        if [ -z "$FACT_WIFI" ]; then
            unknown=1
        elif ! printf '%s\n' "$wifi" | /usr/bin/grep -qxF "$FACT_WIFI"; then
            return 1
        fi
    fi

    # `case` rather than `[ -ge ]` with the error swallowed: a non-numeric count
    # makes `[` exit 2, and a `!` in front of that reads as SUCCESS — a probe
    # returning junk would satisfy the condition it was asked about.
    displays=$(scene_field "$name" .when.displays)
    if [ -n "$displays" ]; then
        case "$FACT_DISPLAYS" in
            "" | *[!0-9]*) unknown=1 ;;
            *) [ "$FACT_DISPLAYS" -ge "$displays" ] || return 1 ;;
        esac
    fi

    [ "$unknown" = 0 ] || return 2
    return 0
}

auto_read() { "$JQ" -r "$1 // empty" "$AUTO_STATE" 2>/dev/null; }
auto_matched() { "$JQ" -r --arg n "$1" '(.matched[$n] // false) | tostring' "$AUTO_STATE" 2>/dev/null; }

auto_write() { # $1 = matched object, $2 = owner, $3 = the entry id it owns
    local tmp="$AUTO_STATE.tmp"
    "$JQ" -n --argjson m "$1" --arg o "$2" --arg e "${3:-0}" \
        '{matched:$m,owner:$o,ownerEntry:$e}' >"$tmp" 2>/dev/null \
        && /bin/mv -f "$tmp" "$AUTO_STATE"
}

# One tick. Run by launchd every haus.focus.triggers.interval seconds, and safe
# to run by hand — it is a function of the machine's state, not of how often it
# is called.
auto_tick() {
    local name owner ownerEntry active matched fired rc was
    /bin/mkdir -p "$STATE_DIR"
    # No state file is the first tick after a fresh install or a cleared state
    # dir: every condition reads as "was false", so whatever holds right now is
    # an edge and gets entered. That is what makes a login inside the 09:00
    # window land in the work scene rather than waiting until tomorrow morning.
    [ -f "$AUTO_STATE" ] || printf '{"matched":{},"owner":"","ownerEntry":"0"}\n' >"$AUTO_STATE"

    probe_facts

    owner=$(auto_read .owner)
    ownerEntry=$(auto_read .ownerEntry)
    active=$(scene_active)
    # Ownership survives only while BOTH the name and the entry it was entered
    # under still stand. The name alone would miss you leaving and re-entering
    # the same scene between two ticks, and then the daemon would evict a scene
    # you had just chosen by hand.
    if [ -n "$owner" ] &&
        { [ "$owner" != "$active" ] || [ "$ownerEntry" != "$(scene_entry_id)" ]; }; then
        owner=""
    fi

    matched='{}'
    fired=""
    while IFS= read -r name; do
        [ -n "$name" ] || continue
        scene_matches "$name"
        rc=$?
        was=$(auto_matched "$name")
        case $rc in
            0)
                if [ "$was" != true ] && [ -z "$fired" ]; then fired=$name; fi
                matched=$("$JQ" -n --argjson m "$matched" --arg n "$name" '$m + {($n): true}')
                ;;
            1) matched=$("$JQ" -n --argjson m "$matched" --arg n "$name" '$m + {($n): false}') ;;
            # Cannot say: carry the last answer forward rather than recording a
            # transition. A probe that blinks must not manufacture an edge on
            # the way back, which is what writing `false` here would do.
            *) matched=$("$JQ" -n --argjson m "$matched" --arg n "$name" --argjson v \
                "$([ "$was" = true ] && echo true || echo false)" '$m + {($n): $v}') ;;
        esac
    done < <(scene_names)

    # SPEND THE EDGE BEFORE ACTING ON IT, and this ordering is load-bearing.
    # `apply` exits 1 when the DND keypress has no Accessibility grant, which
    # takes this whole tick with it — so an entry that fails with the write
    # AFTER it would leave the edge unrecorded, and the next tick 30 seconds
    # later would see the same rising edge, try again, fail again, and post the
    # same notification. Forever. Recording first turns that into one attempt
    # per edge: the failure is still visible (a notification, `focus doctor`),
    # and it is a failure that happens once.
    auto_write "$matched" "$owner" "$ownerEntry"

    # Leave before entering, so one tick can hand over: the window that closed
    # and the one that opened are the same minute. `scene_names` is jq's `keys`,
    # which sorts — so when two conditions rise together the first name wins,
    # deterministically, and `--probe` shows you which.
    #
    # Only a DEFINITE no leaves (rc 1). An unknown holds the scene where it is —
    # see scene_matches.
    if [ -n "$owner" ]; then
        scene_matches "$owner"
        if [ $? = 1 ]; then
            # Forget the ownership BEFORE reversing it, for the same reason the
            # edge is spent before acting on it: `scene_off` reaches `apply off`,
            # which exits 1 without an Accessibility grant and takes the tick
            # with it. Recorded afterwards, that would re-run the scene's `hooks
            # off`, re-release the hold and re-post the same notification every
            # thirty seconds, forever — the failure the entry path is written to
            # avoid, arriving through the other door.
            auto_write "$matched" "" 0
            owner=""
            ownerEntry=0
            scene_off
        fi
    fi

    if [ -n "$fired" ] && [ -z "$owner" ] &&
        [ "$(scene_active)" = off ] && [ "$(focus_state)" != on ]; then
        scene_enter "$fired"
        owner=$fired
        ownerEntry=$(scene_entry_id)
    fi

    auto_write "$matched" "$owner" "$ownerEntry"
}

# The feel-test in one command: what every probe reads right now, and what each
# scene's condition makes of it. Prints the facts unconditionally — including
# the ones no scene asks for — because the first thing you want before writing
# `when.wifi = [ "…" ]` is to see whether this Mac will tell you the SSID at all.
auto_probe() {
    local name owner active mark cond
    FACT_HHMM=$(now_hhmm)
    FACT_DAY=$(now_day)
    FACT_POWER=$(read_power)
    FACT_WIFI=$(read_wifi)
    FACT_DISPLAYS=$(read_displays)
    owner=$(auto_read .owner)
    active=$(scene_active)

    printf 'focus auto — what the trigger daemon reads right now:\n'
    printf '  clock      %s:%s %s\n' "${FACT_HHMM:0:2}" "${FACT_HHMM:2:2}" "$FACT_DAY"
    printf '  power      %s\n' "${FACT_POWER:-unknown}"
    printf '  wifi       %s\n' "${FACT_WIFI:-unreadable (Location Services?) — wifi conditions cannot match}"
    printf '  displays   %s\n' "${FACT_DISPLAYS:-unknown}"
    printf '  now on     %s%s\n' "$(scene_status)" \
        "$([ -n "$owner" ] && [ "$owner" = "$active" ] && echo ' (entered by the daemon)' || echo '')"
    printf 'scenes with a condition:\n'
    ui_load
    if [ -n "$UI_READY" ]; then
        ui_table_clear
        ui_col scene  6 2 subject right
        ui_col when   8 5 muted   right
        ui_col holds  5 1 accent  never
    fi
    while IFS= read -r name; do
        [ -n "$name" ] || continue
        scene_has_when "$name" || continue
        cond=$("$JQ" -r --arg n "$name" '
            (.[$n].when // {}) as $w
            | [ (if ($w.time // "") != "" then $w.time else empty end)
              , (if (($w.days // []) | length) > 0 then ($w.days | join(",")) else empty end)
              , (if (($w.wifi // []) | length) > 0 then ("wifi " + ($w.wifi | join("/"))) else empty end)
              , (if ($w.power // "any") != "any" then ("power " + $w.power) else empty end)
              , (if ($w.displays // null) != null then ("displays>=" + ($w.displays | tostring)) else empty end)
              ] | join(" · ")' "$SCENES" 2>/dev/null)
        scene_matches "$name"
        case $? in
            0) mark="holds" ;;
            1) mark="-" ;;
            *) mark="can't tell — a probe above is blank" ;;
        esac
        if [ -n "$UI_READY" ]; then ui_trow "$name" "$cond" "$mark"
        else printf '  %-14s %-46s %s\n' "$name" "$cond" "$mark"; fi
    done < <(scene_names)
    if [ -n "$UI_READY" ]; then ui_table_data 2; fi
    printf 'A condition that holds is not the same as one that fires: entry happens on\n'
    printf 'the edge where it turns true, and only from a Mac with no scene on.\n'
}

doctor() {
    echo "focus doctor — the one-time setup, checked:"

    local pstate=""
    if pounce_focus_available; then
        echo "  [ok] the launcher's Pounce.app has the focus subcommand — focus rides its TCC grants"
        echo "       (grant Accessibility + Full Disk Access to Pounce.app once, done)"
        pstate=$("$POUNCE_BIN" focus status 2>/dev/null) || pstate=""
    elif [ -z "$POUNCE_BIN" ]; then
        echo "  [~~] launcher room off — no pounce daemon to forward to; per-surface fallback"
        echo "       (haus.launcher.enable puts one Pounce.app behind every surface)"
    else
        echo "  [~~] this pounce has no 'focus' subcommand — using the per-surface fallback"
        echo "       (needs a pounce with the focus subcommand)"
    fi

    if /usr/bin/defaults read com.apple.symbolichotkeys AppleSymbolicHotKeys 2>/dev/null \
        | grep -qE '^[[:space:]]*175[[:space:]]*='; then
        echo "  [ok] DND symbolic hotkey (175) is bound — nix re-asserts it every rebuild"
    else
        echo "  [!!] hotkey 175 not bound yet — run 'darwin-rebuild switch' (modules/focus binds it at activation)"
    fi

    if [ "$pstate" = on ] || [ "$pstate" = off ]; then
        echo "  [ok] Focus state reads exact through Pounce.app (its Full Disk Access grant)"
    elif /bin/cat "$DB" >/dev/null 2>&1; then
        echo "  [ok] Focus state reads exact (Assertions.json reachable from this context)"
    else
        echo "  [~~] no Full Disk Access here → state falls back to focus's own memory and"
        echo "       can drift if you toggle Focus from Control Center or your phone."
        echo "       Fix: System Settings → Privacy & Security → Full Disk Access, add"
        echo "       Pounce.app (with the launcher on), or else the app that runs focus"
        echo "       (your terminal for the CLI, sketchybar for the pill)."
    fi

    echo "  [??] Accessibility can't be probed without actually toggling. With the"
    echo "       launcher's pounce above, its daemon presses on behalf of every surface"
    echo "       (pill, palette, CLI) — the one grant on Pounce.app is enough."
    echo "       Without it, the app invoking focus needs its own grant (System"
    echo "       Settings → Privacy & Security → Accessibility)."

    # The one thing about `focus 25` that is setup rather than state: with its
    # job unloaded the arm refuses outright, and the fix is a rebuild.
    if "$LAUNCHCTL" print "$(timer_domain)" >/dev/null 2>&1; then
        echo "  [ok] timer: $TIMER_LABEL is loaded — 'focus 25' has something to sleep in"
    else
        echo "  [!!] timer: $TIMER_LABEL is not loaded, so 'focus 25' would refuse."
        echo "       Rebuild once (the agent is installed with the room)."
    fi

    local scenes
    scenes=$(scene_names | /usr/bin/wc -l | /usr/bin/tr -d ' ')
    if [ "$scenes" = 0 ]; then
        echo "  [--] scenes: none declared (haus.focus.scenes) — 'quiet' is the built-in"
    else
        echo "  [ok] scenes: $scenes declared — 'focus scene list' shows them"
        if [ -n "$SWITCH_AUDIO" ] && [ ! -x "$SWITCH_AUDIO" ]; then
            echo "  [!!] scenes: the audio switcher is missing at $SWITCH_AUDIO"
        fi
    fi

    local triggered
    triggered=$("$JQ" -r '[.[] | select((.when.time // "") != ""
        or ((.when.days // []) | length) > 0
        or ((.when.wifi // []) | length) > 0
        or (.when.power // "any") != "any"
        or (.when.displays // null) != null)] | length' "$SCENES" 2>/dev/null)
    if [ "${triggered:-0}" = 0 ]; then
        echo "  [--] triggers: no scene declares 'when' — nothing enters a scene for you"
    else
        echo "  [ok] triggers: $triggered $([ "$triggered" = 1 ] && echo scene || echo scenes) with a condition — 'focus auto --probe'"
        echo "       prints what each probe reads and what every condition makes of it"
        if fact_wanted wifi && [ -z "$(read_wifi)" ]; then
            echo "  [!!] triggers: the Wi-Fi SSID reads empty here, and a wifi condition can"
            echo "       never match without it. macOS gates the SSID behind Location Services:"
            echo "       System Settings → Privacy & Security → Location Services, and allow it"
            echo "       for the app that runs focus (the daemon runs as you, so: your login)."
        fi
    fi

    if [ "$SLACK_ENABLED" = 1 ]; then
        TOK=$(slack_token)
        if [ -z "$TOK" ]; then
            echo "  [!!] slack: no token yet —"
            echo "       $SLACK_TOKEN_HINT"
        elif slack_api auth.test -X POST | "$JQ" -e '.ok' >/dev/null 2>&1; then
            echo "  [ok] slack: token accepted"
        else
            echo "  [!!] slack: API rejected the token (needs scopes users.profile:write + dnd:write)"
        fi
    else
        echo "  [--] slack: disabled (haus.focus.slack.enable)"
    fi
}

# `off` and `toggle` release an active scene rather than only un-quieting: the
# bar pill and the palette command both call `toggle`, and a pill that turns
# quiet off while a caffeinate hold and a switched microphone stay behind is a
# pill that lies about what it just did.
#
# Each of the three ends the fuse as well, and says so by dropping it before it
# acts: every one of them writes the quiet state, which voids a running claim
# anyway, so this only decides whether the bar and the process list find out
# now or at 14:35.
case "${1:-toggle}" in
    on)
        timer_cancel
        apply on
        ;;
    off)
        timer_cancel
        if [ "$(scene_active)" != off ]; then scene_off; else apply off; fi
        ;;
    toggle)
        timer_cancel
        if [ "$(scene_active)" != off ]; then
            scene_off
        elif [ "$(focus_state)" = on ]; then
            apply off
        else
            apply on
        fi
        ;;
    # `status` is the word; `status --raw` is the pill's, and it carries the
    # countdown so one call per tick answers both halves of what the pill draws.
    # The second state read behind it is only paid while a fuse exists, which is
    # exactly when there is a countdown to draw.
    status)
        case "${2:-}" in
            "") focus_state ;;
            --raw)
                TIMER_LEFT=""
                [ -f "$TIMER_FILE" ] && TIMER_LEFT=$(timer_remaining)
                printf '%s\t%s\n' "$(focus_state)" "${TIMER_LEFT:-0}"
                ;;
            *)
                echo "usage: focus status [--raw]" >&2
                exit 64
                ;;
        esac
        ;;
    # The fuse on its own: what is left of it, and the one way to drop it
    # WITHOUT ending the quiet it is burning — "actually, I'll stay quiet".
    timer)
        case "${2:-status}" in
            "" | status) timer_status ;;
            off | cancel)
                if [ -f "$TIMER_FILE" ]; then
                    timer_cancel
                    poke_bar
                    note "timer off — quiet stays on"
                else
                    note "no timer"
                fi
                ;;
            *)
                echo "usage: focus timer [off]" >&2
                exit 64
                ;;
        esac
        ;;
    # launchd's entry point, not a word anybody types — the underscore says so,
    # the same way `awake _run` does.
    _timer) timer_run ;;
    doctor) doctor ;;
    # The launchd tick, and the one command that shows what it sees. `auto` on
    # its own acts; `auto --probe` only ever reads.
    auto)
        case "${2:-tick}" in
            --probe | probe) auto_probe ;;
            tick) auto_tick ;;
            *)
                echo "usage: focus auto [--probe]" >&2
                exit 64
                ;;
        esac
        ;;
    # Entering or leaving a scene ends the fuse: a scene owns the whole state
    # while it runs, and a countdown left ticking under one would be counting
    # down to an un-quiet the scene never asked for. `list` and `status` change
    # nothing, so they keep it.
    scene)
        case "${2:-status}" in
            "" | status | list) ;;
            *) timer_cancel ;;
        esac
        case "${2:-status}" in
            "" | status) scene_status ;;
            list) scene_list ;;
            off) scene_off ;;
            toggle) scene_toggle "${3:-}" ;;
            *) scene_enter "$2" ;;
        esac
        ;;
    # A duration is a word too: `focus 25` is the quiet switch with a fuse on
    # it. Last, so it can never shadow a verb — and it is the only arm that
    # fails into the usage text, which is what makes a typo'd verb readable
    # instead of "unknown duration".
    *)
        if TIMER_SECONDS=$(parse_minutes "$1"); then
            timer_arm "$TIMER_SECONDS"
        else
            echo "usage: focus [on|off|toggle|status [--raw]|doctor]" >&2
            echo "       focus <minutes>   quiet, then off again — 25 · 25m · 90min · 1h" >&2
            echo "       focus timer [off] what is left of it (off keeps the quiet)" >&2
            echo "       focus scene [<name>|toggle <name>|off|list|status]" >&2
            echo "       focus auto [--probe]" >&2
            exit 64
        fi
        ;;
esac
