#!/bin/bash
# focus — one switch for quiet, and the named states around it. Turns macOS Do
# Not Disturb on/off by pressing the symbolic hotkey nix-darwin declared (ID
# 175, ⌃⌥⇧⌘F13), sets/restores your Slack status, and runs any host hooks. The
# bar pill, the pounce palette command, and the CLI all drive this one script,
# so no two surfaces can ever disagree about what a toggle does.
#
# `scene` is the same idea with more than one member: haus.focus.scenes.<name>
# declares a state (quiet · awake · an input device · apps · hooks) and this
# script enters and leaves it. `quiet` is the built-in one, which is why
# `focus scene quiet` is spelled as an alias of `focus on` rather than as a
# second copy of it — quiet's state IS the DND state, and reading it twice is
# how a pill starts lying.
#
# GENERATED by modules/focus/default.nix (@var@ substituted at build time).
set -uo pipefail

JQ="@jq@"
STATE_DIR="$HOME/.local/state/focus"
STATE_FILE="$STATE_DIR/state"
SCENE_FILE="$STATE_DIR/scene"
SCENE_PREV="$STATE_DIR/scene-prev.json"
SCENE_PID="$STATE_DIR/scene-caffeinate.pid"
AUTO_STATE="$STATE_DIR/auto.json"
SCENES="@scenes@"
SWITCH_AUDIO="@switchAudio@" # empty unless some scene names an input device

# The trigger probes, each overridable the way modules/core/awake.sh does it —
# the suite (test/focus-auto.sh) stubs every one of them, which is how the
# decision logic below is tested on a machine that is not a Mac. Nothing else
# sets these.
DATE="${FOCUS_DATE_BIN:-/bin/date}"
PMSET="${FOCUS_PMSET_BIN:-/usr/bin/pmset}"
NETWORKSETUP="${FOCUS_NETWORKSETUP_BIN:-/usr/sbin/networksetup}"
SYSTEM_PROFILER="${FOCUS_SYSTEM_PROFILER_BIN:-/usr/sbin/system_profiler}"
# The displays room's helper, when this machine has it: one CGGetActiveDisplayList
# call, instant. Absent, the screen count falls back to system_profiler, which is
# correct and slow — a real second destination rather than a silent degrade, and
# the reason focus does NOT depend on that room.
HAUSDISP="${FOCUS_HAUSDISP_BIN:-/run/current-system/sw/bin/hausdisp}"
DB="$HOME/Library/DoNotDisturb/DB/Assertions.json"
SKETCHYBAR="/opt/homebrew/opt/sketchybar/bin/sketchybar"
BAR_BOTTOM="/run/current-system/sw/bin/bar-bottom"

# Must match the AppleSymbolicHotKeys 175 binding written by default.nix.
KEY_CODE=@keyCode@

SLACK_ENABLED=@slackEnabled@
SLACK_TOKEN_CMD=@slackTokenCommand@
SLACK_STATUS_TEXT=@slackStatusText@
SLACK_STATUS_EMOJI=@slackStatusEmoji@
SLACK_SNOOZE=@slackSnooze@
SLACK_SNOOZE_MINUTES=1440 # failsafe cap; turning it off ends it earlier
HOOKS=(@hooks@)

# The stable-signed pounce copy (modules/launcher keeps its TCC grants alive
# across rebuilds). When it's new enough to have the `focus` subcommand, focus
# rides its Accessibility + Full Disk Access grants for the press AND the
# state read — one pair of checkboxes covers every surface. The probe greps
# --help because an OLDER pounce treats unknown args as ClientMode and would
# open the palette; never call `focus` unprobed.
POUNCE_SIGNED="$HOME/.local/state/pounce/Pounce.app/Contents/MacOS/pounce"
pounce_focus_available() {
    [ -x "$POUNCE_SIGNED" ] && "$POUNCE_SIGNED" --help 2>/dev/null | grep -q "focus status"
}

note() { printf 'focus: %s\n' "$*" >&2; }
notify() { /usr/bin/osascript -e "display notification \"$1\" with title \"focus\"" >/dev/null 2>&1 || true; }
poke_bar() {
    [ -x "$SKETCHYBAR" ] && "$SKETCHYBAR" --trigger focus_change >/dev/null 2>&1 || true
    [ -x "$BAR_BOTTOM" ] && "$BAR_BOTTOM" --trigger focus_change >/dev/null 2>&1 || true
}

# on|off. Exact when the signed pounce can report it (its FDA grant) or when
# Assertions.json is readable directly (the calling app's own FDA); otherwise
# falls back to our own last write. Blind spots in fallback mode: toggles
# made from Control Center or another device.
focus_state() {
    local s db
    if pounce_focus_available; then
        s=$("$POUNCE_SIGNED" focus status 2>/dev/null) || s=""
        case "$s" in on | off)
            echo "$s"
            return
            ;;
        esac
    fi
    db=$(/bin/cat "$DB" 2>/dev/null || true)
    if [ -n "$db" ]; then
        if printf '%s' "$db" | "$JQ" -e '(.data[0].storeAssertionRecords // []) | length > 0' >/dev/null 2>&1; then
            echo on
        else
            echo off
        fi
        return
    fi
    /bin/cat "$STATE_FILE" 2>/dev/null || echo off
}

# Press the DND chord. Preferred: `pounce focus toggle` — since pounce 0.4.3
# the CLI forwards the press to the resident daemon whenever the calling
# context lacks the grant (TCC checks the RESPONSIBLE process — sketchybar
# for the pill, your terminal for the CLI — never the pounce binary itself),
# so the one Accessibility checkbox on the signed Pounce.app covers every
# surface. Fallback: System Events — only without a focus-capable pounce;
# then the keystroke is attributed to the app that invoked focus.
press_hotkey() {
    if pounce_focus_available && "$POUNCE_SIGNED" focus toggle 2>/dev/null; then
        return 0
    fi
    /usr/bin/osascript -e "tell application \"System Events\" to key code $KEY_CODE using {control down, option down, shift down, command down}" >/dev/null 2>&1
}

slack_token() { /bin/bash -c "$SLACK_TOKEN_CMD" 2>/dev/null || true; }

slack_api() { # $1 method, rest = curl args
    local method=$1
    shift
    /usr/bin/curl -sf --max-time 5 -H "Authorization: Bearer $TOK" "$@" \
        "https://slack.com/api/$method" 2>/dev/null
}

slack_set() { # $1 = on|off
    [ "$SLACK_ENABLED" = 1 ] || return 0
    TOK=$(slack_token)
    if [ -z "$TOK" ]; then
        note "slack: tokenCommand printed nothing — skipping (see 'focus doctor')"
        return 0
    fi
    local prev="$STATE_DIR/slack-prev.json"
    if [ "$1" = on ]; then
        # Stash whatever status was there so turning it off can put it back.
        slack_api users.profile.get \
            | "$JQ" '{profile:{status_text:(.profile.status_text // ""), status_emoji:(.profile.status_emoji // ""), status_expiration:0}}' \
            >"$prev" 2>/dev/null || rm -f "$prev"
        local body
        body=$("$JQ" -n --arg t "$SLACK_STATUS_TEXT" --arg e "$SLACK_STATUS_EMOJI" \
            '{profile:{status_text:$t,status_emoji:$e,status_expiration:0}}')
        slack_api users.profile.set -H "Content-type: application/json; charset=utf-8" -d "$body" \
            | "$JQ" -e '.ok' >/dev/null || note "slack: users.profile.set failed"
        if [ "$SLACK_SNOOZE" = 1 ]; then
            slack_api dnd.setSnooze -d "num_minutes=$SLACK_SNOOZE_MINUTES" \
                | "$JQ" -e '.ok' >/dev/null || note "slack: dnd.setSnooze failed"
        fi
    else
        if [ -f "$prev" ]; then
            slack_api users.profile.set -H "Content-type: application/json; charset=utf-8" -d @"$prev" \
                | "$JQ" -e '.ok' >/dev/null || note "slack: status restore failed"
            rm -f "$prev"
        else
            slack_api users.profile.set -H "Content-type: application/json; charset=utf-8" \
                -d '{"profile":{"status_text":"","status_emoji":""}}' \
                | "$JQ" -e '.ok' >/dev/null || note "slack: status clear failed"
        fi
        if [ "$SLACK_SNOOZE" = 1 ]; then
            slack_api dnd.endSnooze -X POST | "$JQ" -e '.ok' >/dev/null || true
        fi
    fi
}

run_hooks() { # $1 = on|off
    local h
    for h in ${HOOKS[@]+"${HOOKS[@]}"}; do
        "$h" "$1" || note "hook failed (non-fatal): $h"
    done
}

apply() { # $1 = on|off
    local want=$1 cur
    cur=$(focus_state)
    if [ "$cur" != "$want" ]; then
        if ! press_hotkey; then
            note "keypress failed — the app invoking focus needs an Accessibility grant (run 'focus doctor')"
            notify "No Accessibility grant — run 'focus doctor' in a terminal"
            exit 1
        fi
    fi
    /bin/mkdir -p "$STATE_DIR"
    printf '%s\n' "$want" >"$STATE_FILE"
    slack_set "$want"
    run_hooks "$want"
    poke_bar
    note "$want"
}

# ---- scenes ----------------------------------------------------------------
# A scene is data (@scenes@ is a JSON file the module wrote), never generated
# shell — so nothing a desktop or a host writes into a scene can become code
# here. Exactly one scene is active at a time; the name lives in $SCENE_FILE
# and what it displaced lives in $SCENE_PREV.

scene_exists() { "$JQ" -e --arg n "$1" 'has($n)' "$SCENES" >/dev/null 2>&1; }
# `// empty` also swallows a literal `false`, so every boolean field here reads
# as "" when it is off. Test for `= true`, never for `= false`.
scene_field() { "$JQ" -r --arg n "$1" ".[\$n]$2 // empty" "$SCENES" 2>/dev/null; }
scene_names() { "$JQ" -r 'keys[]' "$SCENES" 2>/dev/null; }

# The scene that is on, or "off". It can name a scene the host has since
# deleted from the table, which is exactly why LEAVING one is driven entirely
# off $SCENE_PREV (what the scene displaced) and never off the table: a rebuild
# between entering and leaving must not strand the Mac quiet and on the wrong
# microphone with nothing left that knows to put them back.
scene_active() {
    local s
    s=$(/bin/cat "$SCENE_FILE" 2>/dev/null || true)
    [ -n "$s" ] && echo "$s" || echo off
}

audio_input_get() {
    [ -n "$SWITCH_AUDIO" ] || return 0
    "$SWITCH_AUDIO" -c -t input 2>/dev/null || true
}

audio_input_set() { # $1 = exact device name
    [ -n "$SWITCH_AUDIO" ] || return 0
    "$SWITCH_AUDIO" -t input -s "$1" >/dev/null 2>&1 \
        || note "audio: no input device named \"$1\" — left as it was"
}

# An app is named the way `open -a` takes it — a name, a bundle id, or a path —
# and AppleScript has two references to reach one, so both are TRIED rather than
# guessed at from the shape of the string: a bundle id and a dotted app name
# (`draw.io`) look identical, and a heuristic that picks wrong makes closeOnExit
# silently do nothing. `application id` first because it is the exact one; the
# name form answers `false` for anything macOS doesn't know, so an app that
# exists under neither reads as "not running", which is right.
#
# The name reaches osascript as an ARGUMENT, never spliced into the script text:
# scene data stays data, which is the whole reason the table is JSON the engine
# reads rather than generated shell.
#
# `application X is running` is the one form that answers without launching what
# it asks about — `tell application X to ...` would start it.
app_running() { # $1 = app name, bundle id or path
    /usr/bin/osascript - "$1" <<'EOS' 2>/dev/null | grep -q true
on run argv
    set a to item 1 of argv
    try
        return (application id a is running)
    end try
    return (application a is running)
end run
EOS
}

# The polite quit — the same message ⌘Q sends, so an app with unsaved work still
# gets to put its save sheet up. `ignoring application responses` is what makes
# that safe to do from here: without it osascript waits for the reply, and an
# app showing a sheet doesn't reply until a person dismisses it (or the Apple
# event times out, two minutes later), which would leave the rest of the exit —
# the caffeinate hold, the microphone, the state files — hanging behind a modal.
# ⌘Q from the Dock doesn't wait either. Guarded by `is running` so quitting what
# is already gone can never be what starts it.
app_quit() { # $1 = app name, bundle id or path
    /usr/bin/osascript - "$1" <<'EOS' >/dev/null 2>&1
on run argv
    set a to item 1 of argv
    try
        if application id a is running then
            ignoring application responses
                tell application id a to quit
            end ignoring
        end if
        return
    end try
    if application a is running then
        ignoring application responses
            tell application a to quit
        end ignoring
    end if
end run
EOS
}

# caffeinate outlives this script on purpose (the scene is what holds the
# assertion, not the command that started it). The pid file survives a reboot
# and pids get reused, so releasing checks it is still caffeinate before
# signalling anything.
sleep_hold() {
    sleep_release
    # Detached from this script's stdout/stderr as well as its lifetime, or a
    # caller that captures output (`out=$(focus scene x)`) blocks until the
    # assertion is released.
    /usr/bin/caffeinate -dimsu >/dev/null 2>&1 &
    printf '%s\n' "$!" >"$SCENE_PID"
}

sleep_release() {
    local pid comm
    pid=$(/bin/cat "$SCENE_PID" 2>/dev/null || true)
    if [ -n "$pid" ]; then
        comm=$(/bin/ps -o comm= -p "$pid" 2>/dev/null || true)
        case "$comm" in *caffeinate) /bin/kill "$pid" 2>/dev/null ;; esac
    fi
    /bin/rm -f "$SCENE_PID"
}

# `</dev/null` on every hook and every `open`: the loop's own stdin is the
# process substitution holding the rest of the list, and a hook that reads
# stdin would swallow its successors.
scene_hooks() { # $1 = scene, $2 = on|off
    local h
    while IFS= read -r h; do
        [ -n "$h" ] || continue
        "$h" "$2" </dev/null || note "hook failed (non-fatal): $h"
    done < <(scene_field "$1" '.hooks[]?')
}

# What a scene displaced, written on entry and read on exit. `prev` records the
# world as it was; `took` records which levers this scene actually pulled, so
# leaving reverses exactly those and nothing else — and can do it without the
# scene still existing in the table.
scene_prev_write() { # $1 = sceneDnd, $2 = tookDnd, $3 = tookAudio, $4 = restore
    "$JQ" -n \
        --arg dnd "$(focus_state)" --arg audio "$(audio_input_get)" \
        --argjson sceneDnd "$1" --argjson tookDnd "$2" \
        --argjson tookAudio "$3" --argjson restore "$4" \
        '{dnd:$dnd,audioInput:$audio,sceneDnd:$sceneDnd,tookDnd:$tookDnd,tookAudio:$tookAudio,restore:$restore}' \
        >"$SCENE_PREV" 2>/dev/null || /bin/rm -f "$SCENE_PREV"
}

scene_prev_read() { "$JQ" -r "$1 // empty" "$SCENE_PREV" 2>/dev/null; }

# A second write, because which apps an entry STARTED is only known after it has
# started them — and `prev` has to exist before the DND leg, which can exit. A
# scene that doesn't close its apps writes nothing here, so exit finds no list
# and quits nothing.
scene_prev_took_apps() { # $1 = JSON array of apps this entry launched
    local merged
    merged=$("$JQ" --argjson a "$1" '.tookApps = $a' "$SCENE_PREV" 2>/dev/null) || return 0
    printf '%s\n' "$merged" >"$SCENE_PREV"
}

scene_enter() {
    local name=$1 active
    # `quiet` is the built-in and is not in the table: it is what focus on/off,
    # the pill and the palette command already do.
    if [ "$name" = quiet ]; then
        active=$(scene_active)
        [ "$active" != off ] && scene_off
        apply on
        return
    fi
    if ! scene_exists "$name"; then
        note "no scene named \"$name\""
        scene_list >&2
        exit 64
    fi
    active=$(scene_active)
    if [ "$active" = "$name" ]; then
        note "$name (already)"
        return
    fi
    [ "$active" != off ] && scene_off

    local sceneDnd wantAudio takeDnd takeAudio restore app
    sceneDnd=$([ "$(scene_field "$name" .dnd)" = true ] && echo true || echo false)
    restore=$([ "$(scene_field "$name" .restorePreviousState)" = true ] && echo true || echo false)
    wantAudio=$(scene_field "$name" .audioInput)

    # A scene only TAKES a lever it actually moves. Entering a quiet scene while
    # already quiet must not re-run the Slack leg — `slack_set on` would stash
    # the current (already-quiet) status as the one to restore, and that lie
    # survives until the next un-quiet.
    takeDnd=false
    [ "$sceneDnd" = true ] && [ "$(focus_state)" != on ] && takeDnd=true
    takeAudio=false
    [ -n "$wantAudio" ] && [ "$wantAudio" != "$(audio_input_get)" ] && takeAudio=true

    /bin/mkdir -p "$STATE_DIR"
    scene_prev_write "$sceneDnd" "$takeDnd" "$takeAudio" "$restore"

    # The DND leg first, and the name written only after it: `apply` exits when
    # the keypress has no Accessibility grant, and a scene recorded as ON while
    # nothing about the machine changed is the one failure that outlives the
    # command.
    [ "$takeDnd" = true ] && apply on
    printf '%s\n' "$name" >"$SCENE_FILE"

    [ "$(scene_field "$name" .preventSleep)" = true ] && sleep_hold
    [ "$takeAudio" = true ] && audio_input_set "$wantAudio"

    # Only what this scene actually STARTED is its to close: an app you already
    # had open is not a lever it pulled, the same rule takeDnd and takeAudio
    # follow above. The probe costs an osascript per app, so it is only paid by
    # a scene that asked to close them.
    local closeApps took started
    closeApps=$([ "$(scene_field "$name" .closeApps)" = true ] && echo true || echo false)
    took='[]'
    while IFS= read -r app; do
        [ -n "$app" ] || continue
        started=false
        if [ "$closeApps" = true ] && ! app_running "$app"; then started=true; fi
        if ! /usr/bin/open -a "$app" </dev/null >/dev/null 2>&1; then
            note "could not open \"$app\""
        elif [ "$started" = true ]; then
            took=$("$JQ" -n --argjson t "$took" --arg a "$app" '$t + [$a]')
        fi
    done < <(scene_field "$name" '.apps[]?')
    if [ "$closeApps" = true ]; then scene_prev_took_apps "$took"; fi

    scene_hooks "$name" on
    poke_bar
    note "scene $name"
}

# Leave whatever is on, reversing only the levers the scene took. With no scene
# active this un-quiets, so `focus scene off` means "back to normal" whether or
# not a scene was involved — one thing to remember instead of two.
scene_off() {
    local name
    name=$(scene_active)
    if [ "$name" = off ]; then
        [ "$(focus_state)" = on ] && apply off
        return
    fi

    # Read off `prev` like every other reversal — never off the table — so a
    # scene the host deleted mid-flight still closes what it opened. Read HERE
    # and quit at the very end: the levers below all read this same file, and an
    # app is the one thing on the list that can put a dialog between us and them.
    local quitApps
    quitApps=$("$JQ" -r '.tookApps[]? // empty' "$SCENE_PREV" 2>/dev/null)

    scene_hooks "$name" off
    sleep_release

    [ "$(scene_prev_read .tookAudio)" = true ] && audio_input_set "$(scene_prev_read .audioInput)"

    # Un-quiet in two cases and no others: this scene is what made the Mac
    # quiet, or the scene asserts quiet and the host said not to put the
    # previous state back — which is the whole job `restorePreviousState = false`
    # has, and the only way leaving can un-quiet a Mac that was already quiet.
    # No prev file at all (the entry's write failed, or state was hand-edited)
    # means the levers are unknown — and "unknown" has to resolve to the state a
    # person can get back out of, which is not-quiet.
    if [ ! -f "$SCENE_PREV" ]; then
        [ "$(focus_state)" = on ] && apply off
    elif [ "$(scene_prev_read .tookDnd)" = true ] ||
        { [ "$(scene_prev_read .sceneDnd)" = true ] && [ "$(scene_prev_read .restore)" != true ]; }; then
        apply off
    fi

    /bin/rm -f "$SCENE_FILE" "$SCENE_PREV"
    poke_bar

    # Last, with the scene already recorded as off and the bar already repainted:
    # the quit is asynchronous but an app can still take a visible moment to go,
    # and a pill that waits for OBS to finish closing is a pill that looks dead
    # to the second click — which would run this whole function again, against a
    # `prev` file the first pass has since removed.
    while IFS= read -r app; do
        [ -n "$app" ] || continue
        app_quit "$app"
    done <<<"$quitApps"

    note "scene off ($name)"
}

scene_status() {
    local name
    name=$(scene_active)
    if [ "$name" != off ]; then
        echo "$name"
    elif [ "$(focus_state)" = on ]; then
        echo quiet
    else
        echo off
    fi
}

scene_list() {
    local now name desc
    now=$(scene_status)
    printf 'scenes (* = on):\n'
    printf '  %s %-14s %s\n' "$([ "$now" = quiet ] && echo '*' || echo ' ')" quiet \
        "the built-in — what focus on/off, the pill and the palette enter"
    while IFS= read -r name; do
        [ -n "$name" ] || continue
        desc=$(scene_field "$name" .description)
        printf '  %s %-14s %s\n' "$([ "$now" = "$name" ] && echo '*' || echo ' ')" "$name" "$desc"
    done < <(scene_names)
}

# ---- triggers --------------------------------------------------------------
# The half that enters a scene for you. Everything above is driven by a person;
# `focus auto` is one launchd tick asking each scene's `when` whether it holds
# right now, and it obeys exactly one rule: IT NEVER OVERRIDES A STATE YOU CHOSE.
#
# Three mechanics carry that rule, and each is here rather than in the option
# text because each is a decision that had a plausible other answer:
#
#   1. ENTRY IS EDGE-TRIGGERED. A scene is entered on the tick where its
#      condition turns true, never because it is still true. That is the whole
#      reason walking out of an auto-entered scene works: the condition holds,
#      no edge, nothing re-enters it. Level-triggering would re-enter it 30
#      seconds later and there would be no way to say no short of a rebuild.
#   2. ENTRY IS ONLY FROM NEUTRAL — no scene on, not quiet. A scene you entered
#      by hand, or a quiet you switched on, is an opinion; the daemon fills in
#      from nothing and otherwise waits. The edge is spent either way, so it
#      does not pounce the moment you go neutral.
#   3. IT LEAVES ONLY WHAT IT ENTERED, tracked as `owner` — the same "reverse
#      only the levers you pulled" rule the scene engine already follows, one
#      level up. The moment what's active isn't the owner, the daemon has
#      nothing to reverse and says so by forgetting it.

now_hhmm() { "$DATE" +%H%M; }
now_day() { "$DATE" +%a | /usr/bin/tr '[:upper:]' '[:lower:]'; }

win_minutes() { # HH:MM → minutes since midnight. 10# or `09` reads as octal.
    local h=${1%%:*} m=${1##*:}
    printf '%s\n' "$((10#$h * 60 + 10#$m))"
}

# Half-open [start,end): a 09:00-17:00 window is over AT 17:00, not a minute
# later, and an end earlier than the start wraps midnight (22:00-06:00 is one
# night). A window whose ends are equal can never hold, which is why the module
# asserts against it rather than letting it degrade to silence.
time_in_window() { # $1 = HH:MM-HH:MM, $2 = HHMM now
    local start end now
    start=$(win_minutes "${1%%-*}")
    end=$(win_minutes "${1##*-}")
    now=$((10#${2:0:2} * 60 + 10#${2:2:2}))
    if [ "$start" -le "$end" ]; then
        [ "$now" -ge "$start" ] && [ "$now" -lt "$end" ]
    else
        [ "$now" -ge "$start" ] || [ "$now" -lt "$end" ]
    fi
}

# ---- the probes, one reader each -------------------------------------------
# Every one of them answers "" for "I could not tell", and "" matches nothing:
# a condition whose fact is unknown does not hold. That is the conservative
# direction — an unreadable SSID leaves you where you are instead of entering a
# scene on a guess — and it is why `--probe` and `doctor` both print the raw
# reads, since "no match" and "no answer" look identical from the outside.

read_power() {
    case "$("$PMSET" -g batt 2>/dev/null)" in
        *"'AC Power'"*) echo ac ;;
        *"'Battery Power'"*) echo battery ;;
    esac
}

# `networksetup -getairportnetwork <device>` is the supported read, and the
# device is whatever this Mac calls its Wi-Fi port (en0 on most, en1 on some) —
# so it is looked up rather than assumed. macOS can refuse the SSID (Location
# Services), and it refuses by answering "You are not associated with an AirPort
# network", which is indistinguishable from being on none. Hence "" and a doctor
# line, never a guess.
read_wifi() {
    local dev out
    dev=$("$NETWORKSETUP" -listallhardwareports 2>/dev/null \
        | /usr/bin/awk '/^Hardware Port: Wi-Fi$/ { getline; print $2; exit }')
    [ -n "$dev" ] || return 0
    out=$("$NETWORKSETUP" -getairportnetwork "$dev" 2>/dev/null) || return 0
    case "$out" in
        "Current Wi-Fi Network: "*) printf '%s\n' "${out#Current Wi-Fi Network: }" ;;
    esac
}

# Two destinations, both real: the displays room's helper when this machine has
# it (one CGGetActiveDisplayList call), and system_profiler when it doesn't
# (correct, and slow enough to notice — which is what `triggers.interval`'s
# description tells you to raise the interval for).
read_displays() {
    local out n
    if [ -x "$HAUSDISP" ]; then
        out=$("$HAUSDISP" list 2>/dev/null | /usr/bin/head -1)
        case "$out" in
            "active displays: "*)
                printf '%s\n' "${out#active displays: }"
                return
                ;;
        esac
    fi
    n=$("$SYSTEM_PROFILER" -json SPDisplaysDataType 2>/dev/null \
        | "$JQ" '[.SPDisplaysDataType[]?.spdisplays_ndrvs[]?] | length' 2>/dev/null) || return 0
    case "$n" in "" | 0) return 0 ;; esac
    printf '%s\n' "$n"
}

# Does ANY scene ask about this fact? A probe nobody's condition names is never
# run — the same rule that keeps switchaudio-osx out of the closure until a
# scene names an input device, one layer up at runtime.
fact_wanted() { # $1 = power|wifi|displays
    case "$1" in
        power) "$JQ" -e 'any(.[]?; (.when.power // "any") != "any")' "$SCENES" >/dev/null 2>&1 ;;
        wifi) "$JQ" -e 'any(.[]?; ((.when.wifi // []) | length) > 0)' "$SCENES" >/dev/null 2>&1 ;;
        displays) "$JQ" -e 'any(.[]?; (.when.displays // null) != null)' "$SCENES" >/dev/null 2>&1 ;;
    esac
}

# Read once per tick, into globals, because `scene_matches` runs per scene and a
# probe in a command substitution can't memoize (the subshell keeps the cache).
# Six scenes must not mean six `system_profiler` runs.
FACT_HHMM=""
FACT_DAY=""
FACT_POWER=""
FACT_WIFI=""
FACT_DISPLAYS=""

probe_facts() {
    FACT_HHMM=$(now_hhmm)
    FACT_DAY=$(now_day)
    FACT_POWER=""
    FACT_WIFI=""
    FACT_DISPLAYS=""
    fact_wanted power && FACT_POWER=$(read_power)
    fact_wanted wifi && FACT_WIFI=$(read_wifi)
    fact_wanted displays && FACT_DISPLAYS=$(read_displays)
    return 0
}

scene_has_when() { # a scene with no condition is entered by a person and nothing else
    "$JQ" -e --arg n "$1" '
        (.[$n].when // {}) as $w
        | ($w.time // "") != ""
            or (($w.days // []) | length) > 0
            or (($w.wifi // []) | length) > 0
            or ($w.power // "any") != "any"
            or ($w.displays // null) != null
    ' "$SCENES" >/dev/null 2>&1
}

# Every condition a scene declares has to hold — they are ANDed, and a scene
# that declares none never matches at all. Reads the facts `probe_facts` took,
# so a whole tick sees ONE consistent picture of the machine.
scene_matches() { # $1 = scene name
    local name=$1 window days power displays wifi
    scene_has_when "$name" || return 1

    window=$(scene_field "$name" .when.time)
    if [ -n "$window" ]; then
        time_in_window "$window" "$FACT_HHMM" || return 1
    fi

    days=$(scene_field "$name" '.when.days[]?')
    if [ -n "$days" ]; then
        printf '%s\n' "$days" | /usr/bin/grep -qxF "$FACT_DAY" || return 1
    fi

    power=$(scene_field "$name" .when.power)
    if [ -n "$power" ] && [ "$power" != any ]; then
        if [ -z "$FACT_POWER" ] || [ "$power" != "$FACT_POWER" ]; then return 1; fi
    fi

    wifi=$(scene_field "$name" '.when.wifi[]?')
    if [ -n "$wifi" ]; then
        [ -n "$FACT_WIFI" ] || return 1
        printf '%s\n' "$wifi" | /usr/bin/grep -qxF "$FACT_WIFI" || return 1
    fi

    displays=$(scene_field "$name" .when.displays)
    if [ -n "$displays" ]; then
        [ -n "$FACT_DISPLAYS" ] || return 1
        [ "$FACT_DISPLAYS" -ge "$displays" ] 2>/dev/null || return 1
    fi
    return 0
}

auto_read() { "$JQ" -r "$1 // empty" "$AUTO_STATE" 2>/dev/null; }
auto_matched() { "$JQ" -r --arg n "$1" '(.matched[$n] // false) | tostring' "$AUTO_STATE" 2>/dev/null; }

auto_write() { # $1 = matched object, $2 = owner
    local tmp="$AUTO_STATE.tmp"
    "$JQ" -n --argjson m "$1" --arg o "$2" '{matched:$m,owner:$o}' >"$tmp" 2>/dev/null \
        && /bin/mv -f "$tmp" "$AUTO_STATE"
}

# One tick. Run by launchd every haus.focus.triggers.interval seconds, and safe
# to run by hand — it is a function of the machine's state, not of how often it
# is called.
auto_tick() {
    local name owner active matched fired
    /bin/mkdir -p "$STATE_DIR"
    # No state file is the first tick after a fresh install or a cleared state
    # dir: every condition reads as "was false", so whatever holds right now is
    # an edge and gets entered. That is what makes a login inside the 09:00
    # window land in the work scene rather than waiting until tomorrow morning.
    [ -f "$AUTO_STATE" ] || printf '{"matched":{},"owner":""}\n' >"$AUTO_STATE"

    probe_facts

    owner=$(auto_read .owner)
    active=$(scene_active)
    if [ -n "$owner" ] && [ "$owner" != "$active" ]; then owner=""; fi

    matched='{}'
    fired=""
    while IFS= read -r name; do
        [ -n "$name" ] || continue
        if scene_matches "$name"; then
            if [ "$(auto_matched "$name")" != true ] && [ -z "$fired" ]; then fired=$name; fi
            matched=$("$JQ" -n --argjson m "$matched" --arg n "$name" '$m + {($n): true}')
        else
            matched=$("$JQ" -n --argjson m "$matched" --arg n "$name" '$m + {($n): false}')
        fi
    done < <(scene_names)

    # SPEND THE EDGE BEFORE ACTING ON IT, and this ordering is load-bearing.
    # `apply` exits 1 when the DND keypress has no Accessibility grant, which
    # takes this whole tick with it — so an entry that fails with the write
    # AFTER it would leave the edge unrecorded, and the next tick 30 seconds
    # later would see the same rising edge, try again, fail again, and post the
    # same notification. Forever. Recording first turns that into one attempt
    # per edge: the failure is still visible (a notification, `focus doctor`),
    # and it is a failure that happens once.
    auto_write "$matched" "$owner"

    # Leave before entering, so one tick can hand over: the window that closed
    # and the one that opened are the same minute. `scene_names` is jq's `keys`,
    # which sorts — so when two conditions rise together the first name wins,
    # deterministically, and `--probe` shows you which.
    if [ -n "$owner" ] && ! scene_matches "$owner"; then
        scene_off
        owner=""
    fi

    if [ -n "$fired" ] && [ -z "$owner" ] &&
        [ "$(scene_active)" = off ] && [ "$(focus_state)" != on ]; then
        scene_enter "$fired"
        owner=$fired
    fi

    auto_write "$matched" "$owner"
}

# The feel-test in one command: what every probe reads right now, and what each
# scene's condition makes of it. Prints the facts unconditionally — including
# the ones no scene asks for — because the first thing you want before writing
# `when.wifi = [ "…" ]` is to see whether this Mac will tell you the SSID at all.
auto_probe() {
    local name owner active mark cond
    FACT_HHMM=$(now_hhmm)
    FACT_DAY=$(now_day)
    FACT_POWER=$(read_power)
    FACT_WIFI=$(read_wifi)
    FACT_DISPLAYS=$(read_displays)
    owner=$(auto_read .owner)
    active=$(scene_active)

    printf 'focus auto — what the trigger daemon reads right now:\n'
    printf '  clock      %s:%s %s\n' "${FACT_HHMM:0:2}" "${FACT_HHMM:2:2}" "$FACT_DAY"
    printf '  power      %s\n' "${FACT_POWER:-unknown}"
    printf '  wifi       %s\n' "${FACT_WIFI:-unreadable (Location Services?) — wifi conditions cannot match}"
    printf '  displays   %s\n' "${FACT_DISPLAYS:-unknown}"
    printf '  now on     %s%s\n' "$(scene_status)" \
        "$([ -n "$owner" ] && [ "$owner" = "$active" ] && echo ' (entered by the daemon)' || echo '')"
    printf 'scenes with a condition:\n'
    while IFS= read -r name; do
        [ -n "$name" ] || continue
        scene_has_when "$name" || continue
        cond=$("$JQ" -r --arg n "$name" '
            (.[$n].when // {}) as $w
            | [ (if ($w.time // "") != "" then $w.time else empty end)
              , (if (($w.days // []) | length) > 0 then ($w.days | join(",")) else empty end)
              , (if (($w.wifi // []) | length) > 0 then ("wifi " + ($w.wifi | join("/"))) else empty end)
              , (if ($w.power // "any") != "any" then ("power " + $w.power) else empty end)
              , (if ($w.displays // null) != null then ("displays>=" + ($w.displays | tostring)) else empty end)
              ] | join(" · ")' "$SCENES" 2>/dev/null)
        if scene_matches "$name"; then mark="holds"; else mark="-"; fi
        printf '  %-14s %-46s %s\n' "$name" "$cond" "$mark"
    done < <(scene_names)
    printf 'A condition that holds is not the same as one that fires: entry happens on\n'
    printf 'the edge where it turns true, and only from a Mac with no scene on.\n'
}

doctor() {
    echo "focus doctor — the one-time setup, checked:"

    if pounce_focus_available; then
        echo "  [ok] signed pounce has the focus subcommand — focus rides its TCC grants"
        echo "       (grant Accessibility + Full Disk Access to Pounce.app once, done)"
    else
        echo "  [~~] no signed pounce with 'focus' — using the per-surface fallback"
        echo "       (needs a pounce with the focus subcommand + launcher.signingIdentity set)"
    fi

    if /usr/bin/defaults read com.apple.symbolichotkeys AppleSymbolicHotKeys 2>/dev/null \
        | grep -qE '^[[:space:]]*175[[:space:]]*='; then
        echo "  [ok] DND symbolic hotkey (175) is bound — nix re-asserts it every rebuild"
    else
        echo "  [!!] hotkey 175 not bound yet — run 'darwin-rebuild switch' (modules/focus binds it at activation)"
    fi

    if /bin/cat "$DB" >/dev/null 2>&1; then
        echo "  [ok] Focus state reads exact (Assertions.json reachable from this context)"
    else
        echo "  [~~] no Full Disk Access here → state falls back to focus's own memory and"
        echo "       can drift if you toggle Focus from Control Center or your phone."
        echo "       Fix: System Settings → Privacy & Security → Full Disk Access, add the"
        echo "       app that runs focus (your terminal for the CLI, sketchybar for the pill)."
    fi

    echo "  [??] Accessibility can't be probed without actually toggling. With the"
    echo "       signed pounce above, its daemon presses on behalf of every surface"
    echo "       (pill, palette, CLI) — the one grant on Pounce.app is enough."
    echo "       Without it, the app invoking focus needs its own grant (System"
    echo "       Settings → Privacy & Security → Accessibility)."

    local scenes
    scenes=$(scene_names | /usr/bin/wc -l | /usr/bin/tr -d ' ')
    if [ "$scenes" = 0 ]; then
        echo "  [--] scenes: none declared (haus.focus.scenes) — 'quiet' is the built-in"
    else
        echo "  [ok] scenes: $scenes declared — 'focus scene list' shows them"
        if [ -n "$SWITCH_AUDIO" ] && [ ! -x "$SWITCH_AUDIO" ]; then
            echo "  [!!] scenes: the audio switcher is missing at $SWITCH_AUDIO"
        fi
    fi

    local triggered
    triggered=$("$JQ" -r '[.[] | select((.when.time // "") != ""
        or ((.when.days // []) | length) > 0
        or ((.when.wifi // []) | length) > 0
        or (.when.power // "any") != "any"
        or (.when.displays // null) != null)] | length' "$SCENES" 2>/dev/null)
    if [ "${triggered:-0}" = 0 ]; then
        echo "  [--] triggers: no scene declares 'when' — nothing enters a scene for you"
    else
        echo "  [ok] triggers: $triggered scene(s) with a condition — 'focus auto --probe'"
        echo "       prints what each probe reads and what every condition makes of it"
        if fact_wanted wifi && [ -z "$(read_wifi)" ]; then
            echo "  [!!] triggers: the Wi-Fi SSID reads empty here, and a wifi condition can"
            echo "       never match without it. macOS gates the SSID behind Location Services:"
            echo "       System Settings → Privacy & Security → Location Services, and allow it"
            echo "       for the app that runs focus (the daemon runs as you, so: your login)."
        fi
    fi

    if [ "$SLACK_ENABLED" = 1 ]; then
        TOK=$(slack_token)
        if [ -z "$TOK" ]; then
            echo "  [!!] slack: tokenCommand printed nothing — stash a token first, e.g."
            echo "       security add-generic-password -s focus-slack -a \$USER -w 'xoxp-…'"
        elif slack_api auth.test -X POST | "$JQ" -e '.ok' >/dev/null 2>&1; then
            echo "  [ok] slack: token accepted"
        else
            echo "  [!!] slack: API rejected the token (needs scopes users.profile:write + dnd:write)"
        fi
    else
        echo "  [--] slack: disabled (haus.focus.slack.enable)"
    fi
}

# `off` and `toggle` release an active scene rather than only un-quieting: the
# bar pill and the palette command both call `toggle`, and a pill that turns
# quiet off while a caffeinate hold and a switched microphone stay behind is a
# pill that lies about what it just did.
case "${1:-toggle}" in
    on) apply on ;;
    off) if [ "$(scene_active)" != off ]; then scene_off; else apply off; fi ;;
    toggle)
        if [ "$(scene_active)" != off ]; then
            scene_off
        elif [ "$(focus_state)" = on ]; then
            apply off
        else
            apply on
        fi
        ;;
    status) focus_state ;;
    doctor) doctor ;;
    # The launchd tick, and the one command that shows what it sees. `auto` on
    # its own acts; `auto --probe` only ever reads.
    auto)
        case "${2:-tick}" in
            --probe | probe) auto_probe ;;
            tick) auto_tick ;;
            *)
                echo "usage: focus auto [--probe]" >&2
                exit 64
                ;;
        esac
        ;;
    scene)
        case "${2:-status}" in
            "" | status) scene_status ;;
            list) scene_list ;;
            off) scene_off ;;
            *) scene_enter "$2" ;;
        esac
        ;;
    *)
        echo "usage: focus [on|off|toggle|status|doctor]" >&2
        echo "       focus scene [<name>|off|list|status]" >&2
        echo "       focus auto [--probe]" >&2
        exit 64
        ;;
esac
