#!/bin/bash
# signal.sh — "has GitHub said anything, and may I stop asking it?"
#
# Two doors, one body. It is INSTALLED at ~/.config/haus/github/signal.sh to be
# SOURCED by the surfaces that watch GitHub, and on PATH as `github-signal` for
# people and for `haus doctor`. Sourcing is the important half: the statusline
# re-renders on every prompt and the bar's pills tick every few seconds, so the
# question "should I fetch" has to cost a couple of `stat`s — two forks on the
# render path, versus the `gh` call and the network round trip that answering it
# any other way would take.
#
# ── the contract a consumer uses ─────────────────────────────────────────────
#
#   haus_gh_covers <slug>...      exit 0 iff EVERY slug given is covered by a
#                                 live hook — `owner/name`, or a bare `owner`
#                                 for a question about a whole org. No slugs is
#                                 not covered: "I know of nothing" must never
#                                 read as "everything is fine".
#   haus_gh_fresh_since <file>    exit 0 iff a delivery landed after <file> was
#                                 written. This is the "refresh NOW" signal, and
#                                 <file> is normally the consumer's own cache.
#
# and the shape at the call site, which is deliberately three lines:
#
#   ttl=$NORMAL
#   [ -s "$MY_COVERED_FLAG" ] && ttl=$HAUS_GH_BACKSTOP
#   haus_gh_fresh_since "$MY_CACHE" && ttl=0
#
# The flag file is the consumer's own, written by its FETCH path — the one place
# that knows which repositories it just asked about. That split is what keeps
# the render path free of both a fork and a policy decision.
#
# ── why coverage EXPIRES ─────────────────────────────────────────────────────
# Coverage is not "a hook is declared", it is "GitHub told us, RECENTLY, that an
# active hook covers this scope, is subscribed to every event we read, and did
# not fail the last delivery it attempted". Every one of those can stop being
# true silently: a hook edited in a browser, a tunnel that died, a DNS record
# someone moved.
#
# So `scopes` is only ever REWRITTEN by a refresh that got a real answer, and a
# consumer treats it as empty once it ages past `HAUS_GH_COVERAGE_MAXAGE`. A
# machine that loses its ability to confirm coverage quietly goes back to
# polling, which is exactly the direction a failure here should fall.
#
# ── no `set` at file scope, and that is load-bearing ─────────────────────────
# `set -u` here would apply to the SOURCING script, not to this file. That is
# not a style point: statusline.sh deliberately runs without `-u` (its render
# path reads a great many optional JSON fields), so a `set -u` reaching it from
# a sourced library would turn the first absent field into a dead statusline on
# every prompt — from a file it never mentions. Everything below is written to
# be correct without it; the CLI half turns it on for itself, after the guard.

# ---- configuration ----------------------------------------------------------
# Generated by the room (modules/github/default.nix) from `haus.github.*`.
# Defaulted here too so the script is runnable — and testable — on a machine
# where the room has never been enabled.
HAUS_GH_STATE="${HAUS_GH_STATE:-$HOME/.local/state/haus/github}"
HAUS_GH_CONFIG="${HAUS_GH_CONFIG:-$HOME/.config/haus/github}"
# shellcheck source=/dev/null
[ -r "$HAUS_GH_CONFIG/config.sh" ] && . "$HAUS_GH_CONFIG/config.sh"
HAUS_GH_BACKSTOP="${HAUS_GH_BACKSTOP:-300}"
HAUS_GH_COVERAGE_REFRESH="${HAUS_GH_COVERAGE_REFRESH:-3600}"
# Three refreshes' grace before coverage lapses: one missed run is a laptop that
# was asleep, three in a row is something actually wrong.
HAUS_GH_COVERAGE_MAXAGE="${HAUS_GH_COVERAGE_MAXAGE:-$((HAUS_GH_COVERAGE_REFRESH * 3))}"
HAUS_GH_HOSTNAME="${HAUS_GH_HOSTNAME:-}"
HAUS_GH_PORT="${HAUS_GH_PORT:-42786}"

HAUS_GH_SCOPES="$HAUS_GH_STATE/scopes"
HAUS_GH_LAST="$HAUS_GH_STATE/last"
HAUS_GH_HOOKS="$HAUS_GH_CONFIG/hooks.tsv"
HAUS_GH_REPORT="$HAUS_GH_STATE/coverage.tsv"

# ---- the sourced half -------------------------------------------------------

# mtime in epoch seconds, 0 when the file isn't there. `stat -f %m` is BSD,
# which is where this runs — but the same two lines as `statusline.sh`'s
# `mtime` and `statusline-refresh.sh`'s, because test/github-signal.bats runs
# this on a GNU box in CI and this file is sourced into both of them.
#
# Why the status is thrown away. On GNU coreutils -f is --file-system and takes
# NO argument, so `%m` is parsed as a second FILE operand: stdout is a
# filesystem block for the real file, stderr an error about `%m`, and the exit
# is 1. Honouring it — which is what `|| m=0` here used to do — answers 0 for
# every file and never reaches the GNU branch, so `haus_gh_covers` returned
# "not covered" for everything on Linux. Fail-closed, which is the safe
# direction and exactly why nobody noticed. Swallow the status and judge the
# TEXT instead: accept the BSD answer only when it is numeric, then try GNU,
# then insist on digits so the caller's arithmetic cannot blow up.
#
# Two other readers of this seam still carry the BSD-only shape —
# `modules/ai/scruff-cache.sh`'s `mtime` and the two inline ones in
# `modules/bar/sketchybar/plugins/github.sh`. Both are macOS-only and neither
# runs in CI, so neither is wrong today; point a suite at one and it will be.
# One fork more than the old version on the missing-file path (three, not two),
# paid only when the bridge is on and no delivery has arrived yet.
haus_gh_mtime() {
  local m
  m=$(stat -f %m "$1" 2>/dev/null || true)
  case "$m" in '' | *[!0-9]*) m=$(stat -c %Y "$1" 2>/dev/null || echo 0) ;; esac
  case "$m" in '' | *[!0-9]*) m=0 ;; esac
  printf '%s' "$m"
}

# exit 0 iff every slug given is covered. An `owner/name` is covered by a hook
# on `owner` (an org hook covers repositories created after it, which is most of
# the value of one) or by a hook on that exact repository.
haus_gh_covers() {
  [ "$#" -gt 0 ] || return 1
  local scopes_at now slug owner
  scopes_at=$(haus_gh_mtime "$HAUS_GH_SCOPES")
  [ "$scopes_at" -gt 0 ] || return 1
  [ -s "$HAUS_GH_SCOPES" ] || return 1
  now=$(date +%s)
  [ $((now - scopes_at)) -lt "$HAUS_GH_COVERAGE_MAXAGE" ] || return 1
  for slug in "$@"; do
    [ -n "$slug" ] || return 1
    owner="${slug%%/*}"
    grep -qxF "$slug" "$HAUS_GH_SCOPES" 2>/dev/null && continue
    grep -qxF "$owner" "$HAUS_GH_SCOPES" 2>/dev/null && continue
    return 1
  done
  return 0
}

# exit 0 iff a delivery arrived after <file> was last written. A missing <file>
# means the consumer has no cache at all, which is its own reason to fetch — so
# this deliberately says "no" and leaves that decision where it belongs.
haus_gh_fresh_since() {
  local at last
  at=$(haus_gh_mtime "$1")
  [ "$at" -gt 0 ] || return 1
  last=$(haus_gh_mtime "$HAUS_GH_LAST")
  [ "$last" -gt "$at" ]
}

# Sourced? Then that is all — no side effects, no output, nothing run.
# ${BASH_SOURCE[0]} differs from $0 exactly when this file was sourced.
if [ "${BASH_SOURCE[0]}" != "${0}" ]; then
  return 0 2>/dev/null || true
fi

# ---- the CLI half -----------------------------------------------------------
# Past the guard, so this is `github-signal` being RUN rather than the library
# being sourced, and the strictness is this process's own.
set -u

export PATH="/run/current-system/sw/bin:/etc/profiles/per-user/${USER:-$(id -un)}/bin:/opt/homebrew/bin:/usr/bin:/bin:$PATH"
GH=$(command -v gh 2>/dev/null || true)
# Set by do_refresh before anything writes a report row; declared here so `set -u`
# has something to see on every other path through the file.
REPORT_TMP=""

usage() {
  cat <<'EOF'
github-signal — what this Mac knows about its GitHub webhook bridge

usage:
  github-signal status              human summary: receiver, coverage, last delivery
  github-signal covers <slug>...    exit 0 if every slug is covered by a live hook
  github-signal since <file>        exit 0 if a delivery landed after <file>
  github-signal refresh [--force]   re-ask GitHub about the declared hooks
  github-signal check               exit 0 only if every declared hook was
                                    confirmed healthy, recently. Reads the cached
                                    report; never calls out, never writes
  github-signal drift               print what is wrong with each declared hook
                                    and the gh command that fixes it, one per
                                    line; silent only when everything is ok

exit codes: 0 ok · 1 no · 2 bad usage · 3 gh unavailable
EOF
}

# Which repositories/orgs a hook at <scope> covers, printed as the scope key the
# `scopes` file uses.
scope_key() {
  case "$1" in
    org:*) printf '%s' "${1#org:}" ;;
    repo:*) printf '%s' "${1#repo:}" ;;
    *) printf '%s' "$1" ;;
  esac
}

scope_api() {
  case "$1" in
    org:*) printf '/orgs/%s/hooks' "${1#org:}" ;;
    repo:*) printf '/repos/%s/hooks' "${1#repo:}" ;;
    *) return 1 ;;
  esac
}

# The `gh` invocation a person runs to close a gap. Printed, never run: this
# room does not write to GitHub (see options.nix).
fix_command() {
  local scope="$1" events="$2" id="$3" api
  api=$(scope_api "$scope") || return 1
  local flags=""
  local e
  for e in ${events//,/ }; do flags="$flags -f 'events[]=$e'"; done
  if [ -n "$id" ]; then
    printf "gh api -X PATCH %s/%s%s" "$api" "$id" "$flags"
  else
    printf "gh api -X POST %s -f 'name=web' -f 'config[url]=https://%s/github' -f 'config[content_type]=json' -f 'config[secret]=<the secret>'%s" \
      "$api" "${HAUS_GH_HOSTNAME:-<your hostname>}" "$flags"
  fi
}

# One hook's verdict. Writes a report row and, when healthy, prints its scope key.
#
# "Healthy" is all four of: it exists, it is active, GitHub's record of its last
# delivery is not a failure, and every declared event is subscribed. The last one
# is the whole reason this asks GitHub rather than trusting the declaration: a
# hook missing one event looks perfect from the outside and silently never
# delivers the state you check most.
check_hook() {
  local scope="$1" want="$2" api json hook id active status have missing e
  api=$(scope_api "$scope") || { report "$scope" "bad-scope" ""; return 1; }

  json=$("$GH" api "$api" 2>/dev/null) || { report "$scope" "unreadable" ""; return 1; }

  # Ours is the hook pointing at our hostname; with no hostname configured, any
  # active one. jq's `//` would swallow a legitimately empty selection, so the
  # emptiness check is done in bash where it can be told apart from an error.
  if [ -n "$HAUS_GH_HOSTNAME" ]; then
    hook=$(printf '%s' "$json" | jq -c --arg h "$HAUS_GH_HOSTNAME" \
      'map(select((.config.url // "") | contains($h))) | first' 2>/dev/null)
  else
    hook=$(printf '%s' "$json" | jq -c 'map(select(.active)) | first' 2>/dev/null)
  fi
  if [ -z "$hook" ] || [ "$hook" = "null" ]; then
    report "$scope" "absent" "$(fix_command "$scope" "$want" "")"
    return 1
  fi

  id=$(printf '%s' "$hook" | jq -r '.id // ""')
  active=$(printf '%s' "$hook" | jq -r '.active // false')
  have=$(printf '%s' "$hook" | jq -r '(.events // []) | join(",")')

  missing=""
  for e in ${want//,/ }; do
    case ",$have," in *",$e,"*) ;; *) missing="${missing:+$missing,}$e" ;; esac
  done

  if [ "$active" != "true" ]; then
    report "$scope" "inactive" "gh api -X PATCH $api/$id -F active=true"
    return 1
  fi
  if [ -n "$missing" ]; then
    # PATCHing `events` REPLACES the list, so the fix names the union rather
    # than the missing ones — a fix that silently unsubscribes the events
    # somebody else's tooling relies on is not a fix.
    report "$scope" "missing-events:$missing" "$(fix_command "$scope" "$have,$missing" "$id")"
    return 1
  fi
  # Is it actually DELIVERING? Asked of the deliveries endpoint rather than the
  # hook's own `last_response`, which is the obvious field and is `null` on an
  # organisation hook — measured 2026-08-25 against a hook that had answered 200
  # four times in the preceding twenty minutes. Trusting it would have made this
  # whole check dead code on exactly the hooks that matter most here, and dead
  # code that always says "fine".
  #
  # This is the one question that catches a tunnel which died while the hook
  # stayed perfectly configured — the failure the backstop exists for, found an
  # hour earlier than the backstop would find it.
  status=$("$GH" api "$api/$id/deliveries?per_page=1" \
    --jq '.[0] | "\(.status_code)"' 2>/dev/null) || status=""
  case "$status" in
    "" | null)
      # No delivery has ever been attempted (a hook created minutes ago), or
      # GitHub would not say. Neither is evidence of a fault, and coverage
      # expiring is what covers us if it turns out to be one.
      ;;
    2*) ;;
    *)
      report "$scope" "last-delivery:$status" "check the tunnel: github-signal status"
      return 1
      ;;
  esac

  report "$scope" "ok" ""
  scope_key "$scope"
  return 0
}

report() { printf '%s\t%s\t%s\n' "$1" "$2" "$3" >>"$REPORT_TMP"; }

do_refresh() {
  local force="${1:-}"
  [ -n "$GH" ] || return 3
  [ -s "$HAUS_GH_HOOKS" ] || return 1
  mkdir -p "$HAUS_GH_STATE"

  if [ "$force" != "--force" ]; then
    local at
    at=$(haus_gh_mtime "$HAUS_GH_REPORT")
    [ "$at" -gt 0 ] && [ $(($(date +%s) - at)) -lt "$HAUS_GH_COVERAGE_REFRESH" ] && return 0
  fi

  REPORT_TMP=$(mktemp "$HAUS_GH_STATE/.coverage.XXXXXX") || return 1
  local scopes_tmp
  scopes_tmp=$(mktemp "$HAUS_GH_STATE/.scopes.XXXXXX") || { rm -f "$REPORT_TMP"; return 1; }

  local scope events key ok=0 asked=0
  while IFS=$'\t' read -r scope events; do
    [ -n "$scope" ] || continue
    asked=$((asked + 1))
    if key=$(check_hook "$scope" "$events"); then
      printf '%s\n' "$key" >>"$scopes_tmp"
      ok=$((ok + 1))
    fi
  done <"$HAUS_GH_HOOKS"

  mv -f "$REPORT_TMP" "$HAUS_GH_REPORT"
  # `scopes` is rewritten only when GitHub actually answered about every hook.
  # A partial answer leaves the old file to age out rather than half-revoking
  # coverage on the strength of one failed call. See the header.
  if [ "$asked" -gt 0 ] && [ "$ok" -eq "$asked" ]; then
    mv -f "$scopes_tmp" "$HAUS_GH_SCOPES"
  else
    rm -f "$scopes_tmp"
  fi
  return 0
}

case "${1:-status}" in
  covers)
    shift
    haus_gh_covers "$@"
    ;;

  since)
    [ "${2:-}" ] || { usage >&2; exit 2; }
    haus_gh_fresh_since "$2"
    ;;

  refresh)
    do_refresh "${2:-}"
    ;;

  check)
    # Read-only, and deliberately so — this is what `haus doctor`'s card asks,
    # and a check that refreshes would make `haus doctor` rewrite the very file
    # three other surfaces read to decide whether to poll, plus one API call per
    # hook. Never confirmed reads as NOT done, which is the honest answer on a
    # machine that has not managed to ask yet.
    [ -s "$HAUS_GH_REPORT" ] || exit 1
    at=$(haus_gh_mtime "$HAUS_GH_REPORT")
    [ "$at" -gt 0 ] && [ $(($(date +%s) - at)) -lt "$HAUS_GH_COVERAGE_MAXAGE" ] || exit 1
    ! awk -F'\t' '$2 != "ok" { found = 1 } END { exit !found }' "$HAUS_GH_REPORT"
    ;;

  drift)
    do_refresh >/dev/null 2>&1
    if [ ! -s "$HAUS_GH_REPORT" ]; then
      printf '# nothing has been confirmed yet — run `github-signal refresh --force`\n'
      exit 0
    fi
    # EVERY non-ok row, including the ones with no command to offer. `unreadable`
    # (gh logged out, offline, rate-limited) and `bad-scope` (a scope missing its
    # `org:`/`repo:` prefix) have no fix to print, and printing only the fixable
    # rows made this silent — which made `haus doctor` draw a green tick in the
    # two states a fresh install actually lands in. The deck's rule is that it
    # never draws a tick nothing earned.
    awk -F'\t' '$2 != "ok" { print ($3 != "" ? $3 : "# " $1 ": " $2) }' "$HAUS_GH_REPORT"
    ;;

  status)
    printf 'receiver   '
    if nc -z 127.0.0.1 "$HAUS_GH_PORT" >/dev/null 2>&1; then
      printf 'listening on 127.0.0.1:%s\n' "$HAUS_GH_PORT"
    else
      printf 'not listening on 127.0.0.1:%s\n' "$HAUS_GH_PORT"
    fi

    printf 'hostname   %s\n' "${HAUS_GH_HOSTNAME:-(none configured)}"

    printf 'last       '
    if [ -s "$HAUS_GH_LAST" ]; then
      IFS=$'\t' read -r at event scope _ <"$HAUS_GH_LAST"
      printf '%s · %s · %s ago\n' "$event" "${scope:--}" \
        "$(( ($(date +%s) - at) / 60 )) min"
    else
      printf 'no delivery has ever arrived\n'
    fi

    do_refresh >/dev/null 2>&1
    printf 'hooks\n'
    if [ -s "$HAUS_GH_REPORT" ]; then
      while IFS=$'\t' read -r scope verdict fix; do
        printf '  %-28s %s\n' "$scope" "$verdict"
        [ -n "$fix" ] && printf '  %-28s   fix: %s\n' "" "$fix"
      done <"$HAUS_GH_REPORT"
    else
      printf '  none declared (haus.github.hooks)\n'
    fi

    printf 'covered    '
    if [ -s "$HAUS_GH_SCOPES" ] && haus_gh_covers "$(head -n1 "$HAUS_GH_SCOPES")" 2>/dev/null; then
      printf '%s\n' "$(tr '\n' ' ' <"$HAUS_GH_SCOPES" | sed 's/ $//')"
    else
      printf 'nothing — the surfaces that watch GitHub are polling\n'
    fi
    ;;

  -h | --help | help) usage ;;
  *) usage >&2; exit 2 ;;
esac
