# Secrets — declared like everything else, valued nowhere in the repo.
#
# haus ships secretspec (secretspec.dev): a committable secretspec.toml
# declares WHICH secrets a project needs — names and descriptions, never
# values — and a provider supplies the values at runtime. `secretspec run --
# cmd` injects them as env vars into just that process, so nothing lives as
# plaintext files on disk and `secretspec check` on a fresh machine lists
# exactly what still needs entering. That check-and-fill loop is what replaces
# the old hand-carried ~/.secrets directory on the new-Mac checklist.
#
# WHERE values live is personal infrastructure, so it's a host option
# (haus.secrets.provider). The default, "keyring", is the macOS login
# keychain — local, zero accounts, encrypted at rest. Cloud providers (gcsm /
# awssm / bws / onepassword / vault / …) make values follow you across
# machines; their own credential bootstrap (e.g. one gcloud login) becomes the
# single manual step left.
#
# WHICH secrets the machine itself needs used to be nobody's job. A project has
# its own committed manifest, but the rooms — the webhook receiver's HMAC
# secret, a Slack token — could only be reached through a per-room
# `…Command` option the HOST had to write, against a manifest the host also had
# to write, naming secrets the host had to know its rooms wanted. So this room
# receives a deck instead (`haus._contrib.secrets`, modules/secrets/options.nix):
# each room declares the value it needs and why, this room renders every
# declaration into ONE manifest at ~/.config/haus/secretspec.toml, and
# `haus-secret` is the single door all of them read through. The declaration is
# a property of the generation, exactly like the manual-click deck: roll back to
# a system without the github room and its secret stops being asked for.
{
  config,
  lib,
  pkgs,
  username,
  ...
}:

let
  cfg = config.haus.secrets;

  # ---- the deck --------------------------------------------------------------
  # One entry per ROOM-and-thing (the key), which is not the same as one entry
  # per VALUE (the name): two rooms may legitimately want the same token, and
  # the manifest can only carry that name once.
  entries = lib.mapAttrsToList (key: e: e // { inherit key; }) config.haus._contrib.secrets;
  byName = lib.groupBy (e: e.name) entries;

  # Prose arrives as Nix ''…'' blocks, so it is multi-line; both sinks below are
  # one-line-per-secret formats (a TOML string, a TSV field).
  oneLine =
    s:
    lib.concatStringsSep " " (
      builtins.filter (w: builtins.isString w && w != "") (builtins.split "[[:space:]]+" s)
    );

  # Two rooms may SHARE a value — same name, same sentence, one line in the
  # manifest. Two rooms describing the same name differently is a mistake with
  # no honest rendering: the file holds one description, so one room's would
  # silently win and the person filling it in would be told the wrong thing.
  conflicting = lib.filterAttrs (
    _: es:
    lib.length (
      lib.unique (
        map (e: {
          why = oneLine e.why;
          inherit (e) required obtain;
        }) es
      )
    ) > 1
  ) byName;

  # One line per NAME, in the order a person reads them.
  names = lib.sort (a: b: a < b) (lib.attrNames byName);
  declaration = name: lib.head byName.${name};

  manifest = ''
    # Generated by haus — every secret the ROOMS on this Mac declared, through
    # haus._contrib.secrets. Do not edit: a rebuild rewrites it, and a value
    # entered here would be a plaintext secret in a file. Values live in the
    # provider (${
      if cfg.provider == null then "whatever ~/.config/secretspec/config.toml names" else cfg.provider
    });
    # `haus-secret --check` fills them in, `haus-secret --list` says what each is for.
    [project]
    name = "${cfg.project}"
    revision = "1.0"
    # Stated rather than inherited: an agent reading a value out of this machine
    # has to write down why first, and that should not quietly change with a
    # secretspec default. haus-secret never supplies the reason for a read.
    require_reason = "agents"

    [profiles.default]
    ${lib.concatMapStringsSep "\n" (
      name:
      let
        e = declaration name;
      in
      "${name} = { description = ${builtins.toJSON (oneLine e.why)}, required = ${
        if e.required then "true" else "false"
      } }"
    ) names}
  '';

  # `haus-secret --list`'s source: key(s), name, required, why, obtain. A file
  # rather than a table inside the script for the same reason the permissions
  # deck is JSON — the script is substituted, not generated, and this is the one
  # part of it that changes with the configuration.
  table = pkgs.writeText "haus-secret-table.tsv" (
    lib.concatMapStrings (
      name:
      let
        e = declaration name;
      in
      "${lib.concatMapStringsSep "," (x: x.key) byName.${name}}\t${name}\t${
        if e.required then "1" else "0"
      }\t${oneLine e.why}\t${if e.obtain == null then "" else oneLine e.obtain}\n"
    ) names
  );

  # Does this machine's provider key an "always allow" to the reading BINARY?
  # The login keychain does, which is what makes an innocent-looking presence
  # check able to raise a modal dialog after any rebuild that moves secretspec's
  # store path (AGENTS.md's own secretspec gotcha). Unknown counts as yes: with
  # `provider = null` the answer lives in a file the user hand-manages, and the
  # safe assumption is the one that never interrupts them.
  providerItemAcl = if cfg.provider == null || lib.hasPrefix "keyring" cfg.provider then "1" else "0";

  # `uiSh` is snug's bash painter, substituted rather than inherited: this
  # binary is exec'd directly by launchd agents, by `haus doctor` and by a person
  # at a prompt, so there is no `haus` wrapper above it to pass HAUS_UI_SH down.
  # The script loads it lazily and degrades to plain blocks without it — a
  # machine whose pin predates it still prints the listing.
  hausSecret = pkgs.runCommand "haus-secret" { } ''
    mkdir -p $out/bin
    substitute ${./haus-secret.sh} $out/bin/haus-secret \
      --subst-var-by secretspec ${pkgs.secretspec}/bin/secretspec \
      --subst-var-by table ${table} \
      --subst-var-by uiSh ${pkgs.snug}/share/ui.sh \
      --subst-var-by providerItemAcl ${providerItemAcl}
    chmod 555 $out/bin/haus-secret
  '';

  # The costs the rooms themselves named, for the one card that stands for all
  # of them. Deduplicated: two rooms wanting the same token usually describe the
  # same loss twice.
  costs = lib.unique (builtins.filter (c: c != "") (map (e: oneLine e.cost) entries));
in
{
  assertions = [
    {
      assertion = conflicting == { };
      message =
        "haus._contrib.secrets: one secret name, two different declarations — a manifest can only hold one description per name, so the rooms have to agree or use different names. "
        + lib.concatStringsSep " " (
          lib.mapAttrsToList (
            name: es: "${name} is declared by ${lib.concatMapStringsSep ", " (e: e.key) es}."
          ) conflicting
        );
    }
  ];

  # System-wide (like the rest of core's baseline CLI) so haus doctor, sudo, and
  # non-login shells all resolve it. `haus-secret` rides along for a blunter
  # reason: the things that read a value are launchd agents, which get the
  # system profile and never a user shell's PATH.
  environment.systemPackages = [
    pkgs.secretspec
    hausSecret
  ];

  # secretspec's own global config — the file `secretspec config init` would
  # write interactively. Declaring it means a fresh machine needs no init step;
  # provider = null leaves the file alone for hand-management.
  #
  # The manifest beside it is this room's own rendering of the deck, and it is
  # absent rather than empty on a machine where no room asked for anything: an
  # empty profile is a file that invites a hand-edit, and hand-editing it is the
  # one thing that cannot survive a rebuild.
  home-manager.users.${username} = {
    xdg.configFile = lib.mkMerge [
      (lib.mkIf (cfg.provider != null) {
        "secretspec/config.toml".text = ''
          [defaults]
          provider = "${cfg.provider}"
        '';
      })
      (lib.mkIf (entries != [ ]) {
        "haus/secretspec.toml".text = manifest;
      })
    ];
  };

  # ---- the deck's card in the manual-click deck -------------------------------
  # One card for every declared secret rather than one per secret: they are
  # filled in one sitting, by one command, and a wizard that asked five times in
  # a row for the same thing is a wizard people learn to skip.
  #
  # `check` obeys the deck's "never prompt" rule the only way it can, and that
  # is provider-dependent rather than universal: on a cloud provider it is a
  # live `secretspec check --no-prompt`, and on the login keychain — where a
  # presence check IS a read, and a read can raise an ACL dialog — it answers
  # from the stamp `haus-secret --check` wrote. `haus-secret`'s own `ok` has the
  # argument. `detail` therefore names what is WANTED rather than what is
  # missing: it is rendered on this machine's behalf, so it may not ask the
  # provider anything either. `--status` is the live look, and it is in `steps`
  # because a person has to be the one to run it.
  haus._contrib.permissions.secrets-values = lib.mkIf (entries != [ ]) {
    order = 40;
    title = "Secret values — ${toString (lib.length names)} this Mac's rooms asked for";
    why = ''
      Some rooms need a value haus cannot know or invent: a webhook's shared
      secret, a token for an account that is yours. Each room declared what it
      needs and why; the values themselves are entered once, into the store
      `haus.secrets.provider` names${lib.optionalString (cfg.provider != null) " (${cfg.provider})"},
      and never land in a file this machine builds.
    '';
    cost =
      if costs == [ ] then
        "the rooms that asked for them stay switched on and inert"
      else
        lib.concatStringsSep "; " costs;
    check = "haus-secret --ok";
    detail = "haus-secret --wanted | sed 's/^/wanted: /'";
    steps = [
      "haus-secret --list   — what each value is for, and where to get it"
      "haus-secret --status — which ones your provider already has"
      "haus-secret --check  — asks for each missing value and writes it to your provider"
    ];
  };
}
