# haus.snippets — text expansion (espanso), the "@@" → email kind of thing.
#
# Why the Homebrew cask and NOT pkgs.espanso / services.espanso: macOS ties an
# Accessibility (TCC) grant to a stable, signed app identity. The home-manager
# services.espanso module runs the bare nix-store binary ($out/bin/espanso)
# under launchd, so every nixpkgs bump changes that path → the grant is orphaned
# → espanso relaunches, can't confirm Accessibility, and throws up its
# troubleshooting window on login. Running the signed /Applications/Espanso.app
# (cask) instead gives a stable path + Developer ID identity: grant it once and
# it survives reboots and updates — which is also what stops the startup window
# (that window was only ever the symptom of the missing grant).
{
  config,
  lib,
  username,
  ...
}:

let
  panes = import ../lib/settings-panes.nix;
  cfg = config.haus.snippets;

  # espanso reads YAML from ~/.config/espanso. Emit a readable match file from
  # the option; toJSON on each string does the quoting/escaping (so "@@",
  # embedded quotes, colons, and newlines all survive intact).
  matchLine =
    m: "  - trigger: ${builtins.toJSON m.trigger}\n    replace: ${builtins.toJSON m.replace}\n";
  matchesYaml =
    "# Generated by haus.snippets — edit the option, not this file.\nmatches:\n"
    + lib.concatMapStrings matchLine cfg.matches;

  # The cask's CLI lives inside the app bundle — a stable path with the app's
  # signed identity, which is the whole point (see the header).
  espanso = "/Applications/Espanso.app/Contents/MacOS/espanso";
in
lib.mkIf cfg.enable {
  # Espanso's card in core's manual-click deck. The grant is the whole reason
  # this room installs the CASK rather than pkgs.espanso (see the header): a
  # stable signed identity means it is clicked once and never again, which is
  # exactly the promise a card is allowed to make.
  haus._contrib.permissions.snippets-accessibility = {
    order = 40;
    title = "Accessibility — Espanso";
    why = ''
      Text expansion works by watching what you type and typing the replacement
      back. macOS calls both halves Accessibility, and there is no other route
      to either.
    '';
    cost = "no snippet ever fires, and Espanso puts up its own warning window instead";
    # No self-check: espanso answers only for itself, and the CLI's own status
    # reports the daemon rather than the grant. macOS exposes nothing to ask
    # about another app's Accessibility, so this card is honest about being
    # takeable only on the user's word.
    pane = panes.accessibility;
    steps = [
      "Turn Espanso on in the list"
      "Granted once, it stays granted — the identity is stable across rebuilds and nixpkgs bumps"
    ];
  };

  # The signed app, not pkgs.espanso (see the header). A roster entry rather than
  # a bare cask, so it lands in the machine's one list — no key, because you
  # never launch espanso, you type at it.
  haus.roster.espanso = {
    name = lib.mkDefault "Espanso";
    cask = lib.mkDefault "espanso";
  };

  # The card for the job below, in core's services deck — `haus services` and
  # `haus doctor` read it, and `nix flake check`'s services-deck refuses a
  # launchd job that has none. Everything mechanical (label, log, liveness) is
  # read off the plist; this is the half only the room knows.
  haus._contrib.services.espanso = {
    order = 58;
    title = "Text expansion — espanso";
    why = ''
      Watches what you type and types the replacement back, which is the whole
      of what `haus.snippets` does. It is the app bundle rather than a nix-store
      binary so the Accessibility grant survives a rebuild (see the header).
    '';
    cost = "no snippet ever fires — every trigger stays the two characters you typed";
  };

  # The launchd service is declared here, the way every other GUI agent haus
  # ships is — NOT registered by `espanso service register` at activation.
  # That verb writes ~/Library/LaunchAgents/com.federicoterzi.espanso.plist and
  # then drives legacy `launchctl load`, which fails from home-manager's
  # activation context (it runs under `sudo --user`, outside the GUI session's
  # bootstrap): the file landed, the service never did, and the `launchctl
  # kickstart -k` that followed answered "Could not find service" into the
  # 2>/dev/null it was given. Measured 2026-09-20 on a haus-golden guest, two
  # rebuilds in a row — `espanso status` said "espanso is not running" after
  # each, with nothing on screen to say so, and the same register from a plain
  # shell loads fine, which is what made it look like it worked.
  #
  # nix-darwin's own user-agent step bootstraps into gui/<uid> correctly, so it
  # carries this one. The plist is named after its Label, which is the exact
  # path espanso's own register writes, so a machine that ran the old
  # activation (or registered by hand) is replaced in place, `espanso status`
  # keeps finding the service under the name it expects, and the app's own
  # `service register` sees a file and leaves it alone. The program is the app
  # bundle's binary with the `launcher` argument, verbatim from the plist
  # espanso writes for itself, so the signed identity the Accessibility grant
  # is keyed to (see the header) is unchanged.
  #
  # Two orderings this has to survive. On the very first switch the cask lands
  # in nix-darwin's Homebrew step, AFTER the agent is bootstrapped, so the first
  # launch finds no binary and exits non-zero; KeepAlive on failure has launchd
  # try again every ThrottleInterval until it is there, and a launcher that
  # exits cleanly is not relaunched into a second instance. And a config change
  # needs no restart: espanso watches ~/.config/espanso and reloads a changed
  # match file itself, which is why no activation hook is left here.
  launchd.user.agents.espanso = {
    serviceConfig = {
      Label = "com.federicoterzi.espanso";
      # The binary itself, not ../lib/gui-wait.nix's bash wrapper: espanso's own
      # plist starts it bare and it copes with an early login, and a wrapper
      # would make macOS's Login Items notice read "'bash' can run in the
      # background" (measured) — the cold-install register's least explicable
      # modal, back for a room that had escaped it.
      ProgramArguments = [
        espanso
        "launcher"
      ];
      RunAtLoad = true;
      KeepAlive = {
        SuccessfulExit = false;
      };
      ThrottleInterval = 30;
      ProcessType = "Interactive";
      StandardOutPath = "/tmp/espanso.out.log";
      StandardErrorPath = "/tmp/espanso.err.log";
      EnvironmentVariables = {
        LANG = "en_US.UTF-8";
        # A launchd GUI agent's PATH is bare, and espanso's shell extension runs
        # whatever a match names by that PATH — the same search path pounce
        # hands its commands.
        PATH = "/run/current-system/sw/bin:/etc/profiles/per-user/${username}/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/bin:/bin:/usr/sbin:/sbin";
      };
    };
  };

  # A module function so the inner `lib` is home-manager's (carries `lib.hm`);
  # the outer `lib` above is plain nixpkgs lib and has no `.hm`.
  home-manager.users.${username} =
    { lib, ... }:
    {
      home.file = {
        # show_icon parity with the old setup; disable Espanso's ⌥Space hotkeys
        # (search_shortcut & toggle_key) so Pounce leader keys (like ⌥Space L) work.
        ".config/espanso/config/default.yml".text = ''
          show_icon: false
          search_shortcut: OFF
          toggle_key: OFF
        '';
        ".config/espanso/match/default.yml".text = matchesYaml;
      };

      # espanso's first run opens its own wizard — welcome, then "Launch on
      # System startup — Yes (recommended)", then "Add espanso to PATH" (a
      # symlink into /usr/local/bin, behind an admin-password prompt — the app's
      # own question, left to it), then the Accessibility grant. The startup
      # page is gated on a flag in espanso's own key-value store, not on
      # whether a service exists, and its recommended answer runs the same
      # `service register` this module stopped calling: against a service
      # launchd already holds, the `launchctl load -w` inside it fails and the
      # wizard puts up "Operation failed — an error occurred while registering
      # Espanso as a service" (measured 2026-09-20, three times in a row on the
      # golden guest). Answer that question for the machine — haus IS the
      # launch-on-startup — by seeding the flag before the wizard ever asks. A
      # plain file rather than a home.file link, so espanso stays free to
      # rewrite its own store; written only when absent, so a machine that has
      # already answered is left alone. The welcome and Accessibility pages are
      # the user's and stay.
      home.activation.espansoWizardAutoStart = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        kvs="$HOME/Library/Caches/espanso/kvs"
        if [ ! -e "$kvs/has_selected_auto_start_option" ]; then
          $DRY_RUN_CMD /bin/mkdir -p "$kvs"
          $DRY_RUN_CMD /bin/sh -c "/usr/bin/printf 'true' > '$kvs/has_selected_auto_start_option'"
        fi
      '';
    };
}
